### ISSUE TITLE
App not working on the windows

### ISSUE THREAD

**Issue by SemihTrgt** [MerginMaps/input#1088]
Hello, I would compile the application on windows platform and installed the application, but the application does not open.
![Adsız](https://user-images.githubusercontent.com/76948348/104154510-24d60c80-53f6-11eb-9a28-2129751c56ea.png)

**Comment by saberraz** [comment]
Could you check if you have location service enabled:
https://support.microsoft.com/en-us/windows/windows-10-location-service-and-privacy-3a8eee0a-5b0b-dc07-eede-2a5ca1c49088

**Comment by SemihTrgt** [comment]
Location services enabled but  this application not working

**Comment by SemihTrgt** [comment]
I found the source of the problem that [ https://github.com/lutraconsulting/input/pull/625 ](url)  
I installed this version of the application [https://github.com/lutraconsulting/input/pull/625#commitcomment-38740435](url)
This comment is not in master repository

**Comment by saberraz** [comment]
CC @PeterPetrik
