### ISSUE TITLE
individual layer switch on/off

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/input#1258]
you prepare own projects for field survey. in the field, if you have a certain layer that obstructs some feature and you want to disconnect it with a single click and you forgot to make a theme without it, you will be in a dead end. It would be handy therefore have some "advanced features" button in the settings, where we can add the individual layer switch on/off. in the future maybe some other advanced (digitizing, etc) features that are not needed for most users.

**Comment by saberraz** [comment]
Related to https://github.com/lutraconsulting/input/issues/603

**Comment by wonder-sk** [comment]
The idea for implementation is that in "map themes" list, there should be an extra item (e.g. "Show/hide layers") - when clicked, it would open a full page list of map layers, allowing user to set visibility of any layers. Ideally the list should follow the hierarchy of the layer tree as stored in the QGIS project.

Bonus points for providing preview of legend symbol for easier visual identification of layers.
