### ISSUE TITLE
Image preview is not available when a custom path is used

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#1266]
If I use a subfolder (e.g.` @project_path + '/' + 'myfolder'`)  to store my photos, the form comes up with an error that the photo does not exist and also no preview is available.

**Comment by M-Rick** [comment]
This is probably related to this bug.
https://github.com/qgis/QGIS/issues/42280

**Comment by saberraz** [comment]
This can also be related to the expression evaluation issue in Input.

**Comment by tomasMizera** [comment]
This is most probably our internal bug, nothing connected to QGIS

**Comment by tomasMizera** [comment]
`@project_path` should not be used in photo field, see docs https://merginmaps.com/docs/layer/settingup_forms_photo/#how-to-set-up-a-custom-folder-for-storing-photos:~:text=sync%20your%20project!-,Here%20is,-an%20overview%20of

**Comment by rmarzocchi84** [comment]
Same problem using a online photo (hyperlink with web view). 

On QGIS I see the picture correctly 
![image](https://github.com/MerginMaps/input/assets/4061154/ac9ac458-0bbf-4d7d-8ef3-b506633230e4)

On input I see correctly the path, but image preview is not available:
![image](https://github.com/MerginMaps/input/assets/4061154/3566890a-23b4-4290-b269-3f6b57bb14d1)

**Comment by jozef-budac** [comment]
@iiLubos @tomasMizera I am not sure about the configuration here. When I use @project_path variable, I get this error:
![image](https://github.com/MerginMaps/input/assets/83582181/371116be-9148-436a-bf4f-bea90a1adefa)

**Comment by tomasMizera** [comment]
Yeah, according to docs (https://merginmaps.com/docs/layer/settingup_forms_photo/#how-to-set-up-a-custom-folder-for-storing-photos), one should use `@project_home` or `@project_folder` for now
