### ISSUE TITLE
Unsaved changes window pops up even when for no changes

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/input#1410]
Reproduce:
 - open project
 - open form of any already reported feature (do not click edit)
 - hit back button on Android

Experienced:
 - window telling me that I have unsaved changes shows up even though I was not even in edit mode

Expected:
 - form would just close

The same is happening if click `edit` and not change anything, just hit back button. 

On the other hand close button does show this message even when there are changes (is this intended?)

**Comment by PeterPetrik** [comment]
I think there may be error in the hasChanges c++ function in attributecontroller

**Comment by tomasMizera** [comment]
Just discovered this issue again in `dev` version

**Comment by jozef-budac** [comment]
@tomasMizera I can't reproduce this anymore. Can you please recheck?

**Comment by tomasMizera** [comment]
Very well then, let's close it

**Comment by tomasMizera** [comment]
I could reproduce this now on my project `SurveyCorp/millions-vr` on dev.

**Comment by tomasMizera** [comment]
What's the status here @gabriel-bolbotina ?

**Comment by gabriel-bolbotina** [comment]
I tested the issue with the current master (https://github.com/MerginMaps/mobile/pull/4595) and it no longer reproduces.
The issue was fixed by https://github.com/MerginMaps/mobile/issues/3297.

**Comment by IvaKuklica** [comment]
🟢 Testing Summary:
----------------
Application (+ app version, build, operating system)
Dev/OS/app: Samsung Galaxy A53 5G, Android 15/ MM 2026.3.0 - 833251
Dev/OS/app:: IPhone 15 / iOS 26 / MM 2026.3.0 - 26.7.927411

The feature form closed correctly without displaying the "You have unsaved changes" warning dialog in any of the attempts. 
The behaviour matches the expected result
