### ISSUE TITLE
Trigger support for gpkg in Input

### ISSUE THREAD

**Issue by HugoP27** [MerginMaps/input#1414]
Hi Lutra Team

I've set up a trigger for a gpkg in QGIS that updates one table in my geopackage when I update a separate table. 

It works in QGIS, but unfortunately not in Input. Are gpkg triggers supported in Input?

Thanks

**Comment by wonder-sk** [comment]
Do you have a sample file that we could test?

In general triggers in gpkg should not be a problem in Input as such, but I think there may be a problem with syncing when there are some custom triggers (and you may start getting conflict files)

**Comment by HugoP27** [comment]
Hi @wonder-sk 
Thanks for the swift response. 
I've attached the sample. The idea behind the trigger is that the user logs a weekly reading on the 3.1 Flowmeter Monitor layer which will have no labels or symbology, once logged the reading is populated to the latest_reading field in 3.Flowmeter using the trigger. Reason for this is that the user sees the latest reading when clicking on the flowmeter feature. 

Thanks for testing this, if it will cause issues with syncing or not work in Input I will think of a workaround.
[trigger_sample.zip](https://github.com/lutraconsulting/input/files/6511010/trigger_sample.zip)

**Comment by PeterPetrik** [comment]
this is geodiff issue https://github.com/MerginMaps/geodiff/issues/48, closing the ticket
