### ISSUE TITLE
Hide keyboard on project open

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/input#1420]
Steps to reproduce:

 - search for a project
 - open project without closing the keyboard
 - go back to projects list
 
Expected:
 - you are in the home page and search bar is cleaner ✔️ 
 - keyboard is hidden ❎ 

Keyboard is actually visible
 
<img src="https://user-images.githubusercontent.com/22449698/119355523-aa6fa000-bca5-11eb-8c97-258428b5b1ee.gif" width=300>

**Comment by tomasMizera** [comment]
I can replicate this on iOS now

**Comment by jozef-budac** [comment]
@tomasMizera I can't replicate this on android 1.9.0. can you recheck?

**Comment by tomasMizera** [comment]
It is happening on both platforms now

**Comment by PeterPetrik** [comment]
**Cannot** replicate either on iOS or Android v2.2.0
