### ISSUE TITLE
Edit geometry for multipoint layer jumps to different location

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#1441]
In the project tin0/tc04_recording there is a multipoint layer (Vela bodikov). When feature geometry is edited, it jumps to completer different location on the map.

https://user-images.githubusercontent.com/83582181/120280782-6dfcff00-c2b8-11eb-89dc-157a51b840ab.mp4

**Comment by tomasMizera** [comment]
Is this one now fixed with geometry editing @jozef-budac?

**Comment by jozef-budac** [comment]
Yes, it is fixed now
