### ISSUE TITLE
Subscription on iOS

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#1475]
version: 0.9.8 testflight

Testcase 01 - Test F says:
F5. There should be two plans available: Individual and Professional
F6. Prices should appear in the local currency
F7. Select Individual plan
F8. Sign in with your Apple ID
F9. You should be upgraded to the Individual plan

The last step fails with notification:
"Failed to purchase subscription"

**Comment by saberraz** [comment]
@jozef-budac did you have a previous subscription or an ongoing subscription?

**Comment by jozef-budac** [comment]
I didn't have any previous subscription.

**Comment by PeterPetrik** [comment]
if it is on TestFlight , we need to revisit the test, it was always a bit iffy

**Comment by sklencar** [comment]
Ive managed to go through subscription process and get `your purchase was successful` (see screenshoot bellow).
However, I also got Input's notification `Failed to purchase subscription` and plan has not been updated - thats what I can recall from the past. Agree with Peter, it was always a bit iffy.

Anyway, subscription should be processed successfully even for TestFlight version with test-sandbox user, shouldn't be? Any ideas?
 
![IMG_0125](https://user-images.githubusercontent.com/6735606/121872380-7b2cdb80-cd05-11eb-9c87-4668b3d27999.PNG)

**Comment by PeterPetrik** [comment]
as far as I remember "You are all set" is all I was able to get from sandbox/testflight, do not remember why.

**Comment by PeterPetrik** [comment]
We cancelled to offer Apple subscriptions on 13th September 2023, closing this
