### ISSUE TITLE
Hide layers/tables that are set as Private in QGIS Project Properties

### ISSUE THREAD

**Issue by chris9404** [MerginMaps/input#1481]
Currently layers and tables that are set as Private in QGIS Project Properties are still viewable when clicking on More -> Browse Features.
In our case the tables are used as reference for calculations/relationships and are not tied to features specifically, and it would be helpful if we can hide this from the user.

**Comment by dracic** [comment]
When you set the layer as not searchable does it still appear in Browse features? Because I think the logic behind "Private" layer property in QGIS API is different from yours:


Enumerator |   -
-- | --
Searchable | Only for vector-layer, determines if the layer is used in the 'search all layers' locator.
Private | Determines if the layer is meant to be exposed to the GUI, i.e. visible in the layer legend tree.

**Comment by chris9404** [comment]
I see what you mean.
Layers that are not searchable do not appear in the Browse Features section, which is correct, but the tables still appear.
Although from the API you referenced above "Searchable" is only applicable to vector-layers, so that works as intended.

What I have tried is to convert the tables to a Point vector-layer with no XY, and keep it hidden from the user (i.e. not Searchable). Its not an elegant solution, but everything still seems to work and the layers are not seen in Browse Features.
Do you have any other suggestions?

**Comment by chris9404** [comment]
Apologies, after going through the layer list, the actual property that determines whether a layer appears in the Browse Features section is "Identifiable". 
Tables do not have this option, which is why they always appear in Browse Features, regardless of "Private" or "Searchable".

**Comment by dracic** [comment]
Yes, that I can confirm. So tables (and layers with geometry) that are not searchable should not be made visible in "Browse features". Layers can be "identifiable" or "searchable" or both at the same time, or non of that.

**Comment by Koivusto** [comment]
This would be a nice feature. Currently in our project we have quite a few supporting value relation tables which only confuse user if he/she finds them.
