### ISSUE TITLE
Wrong data limit warning for organizations' projects

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#1492]
Then data limit for organization is reached, in INPUT, warning with user subscription appears.
It is strange, as it looks there is still plenty of space for the project, but it isn't

![192491429_463774014967347_865849136584732173_n](https://user-images.githubusercontent.com/83582181/122185317-4c417180-ce8d-11eb-97d6-e821a8fe7212.jpg)

**Comment by PeterPetrik** [comment]
@jozef-budac Is this still the case with workspace update?

**Comment by jozef-budac** [comment]
I can't reproduce this anymore
