### ISSUE TITLE
Range slider limit is 29, even when is set to 30

### ISSUE THREAD

**Issue by jozefbudac** [MerginMaps/input#1497]
INPUT: 0.9.8 releases
OS: both iOS & Android

Steps to reproduce:
1) open project  input-testing/forms_widgets
2) add a feature to POI layer
3) in the form on tab 'Numbers' there is a Range slider, which is set to: min -10, max 30, step 3. But the slider allows do to max 29 and can't be moved further

I am not sure, but I believe this worked in previous versions, so I marked is as regression

**Comment by PeterPetrik** [comment]
still in Input 2.1.1
