### ISSUE TITLE
FeatureForm freezes

### ISSUE THREAD

**Issue by sklencar** [MerginMaps/input#1519]
Feature form freezes (see video bellow) and after a while the app crashes.
The feature form generally feels a bit slow and laggy when it has not small amount of fields. 

It could be performance issue. I could replicate it on Android (tablet), but not on iOS.

test project: _tin1/form_widgets_

https://user-images.githubusercontent.com/6735606/123258220-6b767980-d4f3-11eb-9734-1619a910974a.mp4

**Comment by jozef-budac** [comment]
Not reproducible.
