### ISSUE TITLE
Crash when getting picture from gallery

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#1540]
This bug is only on iOS

Steps:
1) in photo widget choose gallery
2) click on first and then immediately on next picture - the app crashes

**Comment by sklencar** [comment]
@jozef-budac Could you please provide a test project and more detailed info about how to replicate it? I have not managed to replicate it. Thanks

**Comment by jozef-budac** [comment]
It is any project with photo widget. The important thing is simulation is to click on multiple pictures right after each other when using gallery in photo widget

https://user-images.githubusercontent.com/83582181/126124540-c3bfc222-c417-447d-8430-e86faad03b54.MP4

**Comment by tomasMizera** [comment]
@jozef-budac can you still replicate this?

**Comment by jozef-budac** [comment]
yes, I can replicate this even with latest release

**Comment by PeterPetrik** [comment]
still present in v2.4.0
