### ISSUE TITLE
Home page gets very slow if you have a number of projects downloaded

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#1556]
It tries to check the status of the project and it takes ages to load the Home page.

**Comment by NewGraphEnvironment** [comment]
wondering if my issue could be related to this and #1556 

there is still 6G more room in account so can't be too many photos for memory....

not easy to reproduce but in a perfect world we would:

1. have iphone 13 pro max
2. check for but see no notice of recent (or any) update in App store/Account
3. have several large projects downloaded to phone (0.5G to 2G)
4. within active project leave photo size at original but within ignored directory so phones don't see others photos
5. collect 2 days worth of data and photos (maybe 15 sites with 10 photos each)
6. try to sync in map view but the sync wheel never stops spinning (internet speed 10 - 15 mbps)
7. close the app and try to sync in `Projects` view (20 mins to hour each) - no luck
8. go back to the field the next day and collect another more data (3 sites with 10 photos each)
10. try to sync in map view with little spin widget.  wheel spins for over an hour.  close app
11. app hangs on reopening Mergin. Blank white screen with location arrow for a few seconds then just blank white screen. Then app automatically goes to background. Doesn't close but stays hanging in the background forever.

Downloaded backup from the phone to Mac as per these very helpful instructions https://merginmaps.com/docs/manage/missing-data/#next-steps - phew.  was spooked.. Will probably just uninstall and reinstall before starting work in the morning. We are still backing everything up with paper for a bit longer too.  Love these tools though.  The future in our hands. Really wonderful to leverage Q in the field. Thanks!

**Comment by PeterPetrik** [comment]
I even got the massive error if I have more than 20 projects locally loaded
![Screenshot 2023-09-29 at 8 08 56](https://github.com/MerginMaps/input/assets/804608/adebe8af-7bfa-4418-8145-e828d9de0d49)
