### ISSUE TITLE
GPS accuracy popup link is not working

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/input#1581]
Banner used for gps accuracy contains clickable link. Currently clicking on link _only sometimes_ works.

I saw that its internal state is changing each time position is changed (in streaming mode). MouseArea is enabled based on this state so I think this is the problem.

<img width=300 src="https://user-images.githubusercontent.com/22449698/128027505-b695f3e7-aa0a-4ce8-a266-4e0e182f84ec.jpg">

**Comment by wonder-sk** [comment]
Ah yes, I wanted to report this a couple of times already :-) 

While at it, I think we should also change the color of the "Learn more" link, so it is more obvious it is a clickable link...

**Comment by tomasMizera** [comment]
Also: you can open the link when the banner is hidden, when you hit the exact link place

**Comment by tomasMizera** [comment]
Today this bug has occured again - I can click on a space where normally should be the link and even though banner is not visible, I am still redirected to the webpage

**Comment by tomasMizera** [comment]
No longer there

**Comment by tomasMizera** [comment]
Occured again

**Comment by jozef-budac** [comment]
@tomasMizera  I can't reproduce this on my devices
