### ISSUE TITLE
Automatically turn off "Follow me" mode when selecting feature

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/input#1607]
When user is in "auto center on GPS point" mode and he clicks on a feature to select it, Input moves extent to GPS point instead of  the selected feature.

To reproduce:
 - open some project
 - enable "auto center on GPS point"
 - select feature (either from `BrowseData` panel or from map)

Expected:
 - "auto center.." mode is turned off
 - map extent moves to selected feature

Experienced:
 - "auto center" is still turned on
 - map extent thus still follow GPS
 
User needs to turn off the "auto center" mode first in order to see the selected feature.

**Comment by PeterPetrik** [comment]
@tomasMizera isn't this addressed in https://github.com/MerginMaps/input/pull/2614 ?

**Comment by tomasMizera** [comment]
Not sure.. I need to double check

**Comment by PeterPetrik** [comment]
checked, this is fixed by https://github.com/MerginMaps/input/pull/2614
