### ISSUE TITLE
Custom folder for storing photos doesn't work for empty folders

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#1611]
When I have project with custom folder for storing photos in QGIS, and this folder is empty, it is not synchronized to mergin, and also to INPUT. 
When creating a photo feature in INPUT, it shows and error "Cannot copy a photo to working directory"

We should synchronize the empty directory, or INPUT should be able to create a directory in case it is needed.
For testing you can use project input-testing/tc10_custom_photo_directory

Here is configuration of the photo field in the feature

![Screenshot at 2021-08-26 09-51-37](https://user-images.githubusercontent.com/83582181/130923605-1f76e67c-c4fe-426c-823d-ee2fb60c2a15.png)

**Comment by acgtdev** [comment]
This doesn't work out for me. Have been trying to create a empty directory 'photos'. It will be created at local but not in mergin.

**Comment by alexbruy** [comment]
In this particular case the problem is in incorrect configuration of the attachment widget. Expression should be set using data-defined override, not entered directly in the field.

**Comment by PeterPetrik** [comment]
is mergin plugin in QGIS reporting the warning?

**Comment by jozef-budac** [comment]
@tomasMizera With @iiLubos patch, this issue is solved
