### ISSUE TITLE
Travel time

### ISSUE THREAD

**Issue by Fertuesta25** [MerginMaps/input#1625]
It is possible to capture the travel time automatically during the digitization of a tour (line).

**Comment by wonder-sk** [comment]
> It is possible to capture the travel time automatically during the digitization of a tour (line).

How do you mean it to capture travel time? E.g. if you start digitizing a line at 1:00pm and finish digitizing it at 1:20pm, to capture the information that it took 20 min to record that linestring (maybe in a variable)? Or did I get it completely wrong? :slightly_smiling_face:

**Comment by Fertuesta25** [comment]
Correct would be very useful when running lines.

**Comment by tomasMizera** [comment]
Hi @Fertuesta25, it's quite a long time since you reported this ticket. I moved it to our wishlist: https://wishlist.merginmaps.com/p/add-variable-how-long-it-took-to-create-geometry feel free to vote for it if you still need it.
