### ISSUE TITLE
Measurements

### ISSUE THREAD

**Issue by sygys** [MerginMaps/input#1628]
We are using the app to set areas where another companie needs to mow. these areas need to be 1.5 meters wide. so we sail on the canals setting points but there is no way to see the size of the lines you draw in a polygon. There is a scale bar on the bottom but that is offcourse useless when drawing shapes. is there a way you could add the lenght of the line you are drawing? this would help tremendously

**Comment by saberraz** [comment]
You can use Geometry-generator styling in QGIS to set 1.5 m buffer around your features:
https://docs.qgis.org/3.16/en/docs/user_manual/style_library/symbol_selector.html#the-geometry-generator
