### ISSUE TITLE
Wrong price shown to the apple users subscribed before plan price update

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/input#1644]
At the moment, the nextBillPrice is set based on the planID https://github.com/lutraconsulting/input/blob/a29911be7c27945fd5b5f6bc1b16036883e6014f/app/ios/iospurchasing.mm#L159

but the planID price is "new" one (for new user) and not reflecting what actually apple charges for current "subscription". Prooblem is is that same apple planID is reused for both "new" and "old" subscriiption price. 

The approach tried in https://github.com/lutraconsulting/input/pull/1632 is not valid, since it shows CORRECT price but in EUR (not localized). We shoould fix in in way that we take localizedPrize based on the subscriptionID, not planID frmo the apple SDK (if possible)

**Comment by tomasMizera** [comment]
See:  https://developer.apple.com/app-store/subscriptions/#keeping-subscribers
https://help.apple.com/app-store-connect/#/devc9870599e
https://developer.apple.com/documentation/storekit/skpaymentqueuedelegate/3521328-paymentqueueshouldshowpriceconse

**Comment by PeterPetrik** [comment]
We cancelled to offer Apple subscriptions on 13th September 2023, closing this
