### ISSUE TITLE
Update Message Problems.

### ISSUE THREAD

**Issue by Juncus** [MerginMaps/input#1655]
On the login page, I have an update message which went un-noticed as it is partially hidden from view by the word Mergin.
It also seems a little pointless. I have auto-update on and can see the version number in the app. Also, there is no update which should mean I have the latest version. So why does the message appear and partially hidden and why is there no version number on the app store in the update section/whats new. It only gets shown on the browser if you scroll down far enough.
I have the latest version and yet I'm being asked to update? The google play app  does not show the version number.
And after all that I can't login to place I've been using for some time with all the same details.

**Comment by wonder-sk** [comment]
Sorry I am not really sure what you are referring to - could you please provide a screenshot?

**Comment by wonder-sk** [comment]
Ah probably you are referring to this issue? https://github.com/lutraconsulting/input/issues/1488

**Comment by jozef-budac** [comment]
Closing in favor of https://github.com/MerginMaps/input/issues/1488
