### ISSUE TITLE
GPS antenna height

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/input#1710]
For precise measurements with external GPS antenna, it is useful if users can set the height of the antenna above the ground, so that this height is subtracted from the measured elevation in order to get the correct elevation.

In case the antenna height is non-zero, it would be useful to show the height settings in the GUI when recording, so that users are aware of it, and in case they change the height for some reason, it's lower chance that they would forget to adjust it in the app.

There should be a new variable containing the antenna height configuration, in case users want to store that to an attribute.

**Comment by Brent-Edwards** [comment]
This would be a great enhancement and is essential for high accuracy external GPS coordinates.

**Comment by waiotahi** [comment]
+ 1

**Comment by MTrim** [comment]
I agree.... would be a nice feature, when working with external GNSS

**Comment by MTrim** [comment]
any timeline for this feature?
