### ISSUE TITLE
Confusion with GSB and TIF for proj transformation

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#1735]
To replicate the issue:
- Create a project with Openstreetmap (EPSG:3857) and a layer from EPSG:27700
- Input keeps complaining about uk_os_OSTN15_NTv2_OSGBtoETRS.tif
- When you add proj/uk_os_OSTN15_NTv2_OSGBtoETRS.tif it complains about OSTN15_NTv2_OSGBtoETRS.gsb
- Adding both also does not solve the problem.

**Comment by wonder-sk** [comment]
Do we have a testing project? It could be that there are some incompatibilities when project is prepared in QGIS with Proj 7 or 8 (which use .tif for grids) versus what Input needs (Proj 6 which uses .gsb)
