### ISSUE TITLE
Clean up the Input folder under Android

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#1747]
When I browse to` /Internal shared storage/Android/data/uk.co.lutraconsulting/files/` there are several other folders. Would be good to clean the ones we do not want. Unless it is Android templates and we have to have all of them:

![image](https://user-images.githubusercontent.com/2649047/140704401-f125330d-a716-48c3-9f68-6268800dbbc5.png)

**Comment by jozef-budac** [comment]
On newer android versions, user is not allowed to browse that folder anyway, so probably this is not relevant anymore
