### ISSUE TITLE
Unable to get project list in offline mode

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/input#1757]
1. Firstly in online mode, download my project to my device (1:09)
2. Still in online mode trying to open theme, add/edit feature and so on. Everything is normal (1:23)
3. Back to my project (1:30). The project list still there.
4. Switch off data connection (1:40), back to my project, the project list di disappear (1:44). Error message: unable to get the list of projects.
5. Reconnect to the internet (1:58). Input.io refreshing the project list, input.io bring me my project list back (2:06)
6. Switched to offline mode (2:08), back to my project, continue to edit feature in offline mode.

https://user-images.githubusercontent.com/804608/142183260-fcbac715-2537-48f1-b299-88d5e064a683.mp4

InputApp 1.1.0

**Comment by tomasMizera** [comment]
Not reproducible anymore on the latest version, please reopen if you still struggle with this
