### ISSUE TITLE
DateTime field ignores inserted value

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#1795]
In the project jozefbudac/issue_1795, in the time layer, there are multiple date/time fields. The 5th field is not working in INPUT, no value can be inserted into it. The field doesn't have any special settings, just default things created by QGIS. 

Steps to reproduce:
1) download project jozefbudac/issue_1795 and open it
2) open record form in Time layer
3) try to set some value to the last field - no value is stored

https://user-images.githubusercontent.com/83582181/144980809-f0fb3eeb-5f1d-4a08-94ce-10ed899db045.mp4

**Comment by jozef-budac** [comment]
Still present in 1.9.0

**Comment by PeterPetrik** [comment]
this is working on latest master 

https://github.com/MerginMaps/input/assets/804608/c4d2b8c7-0059-42e9-ba1c-d8841b2a5728
