### ISSUE TITLE
unable to create feature while "reuse last value option" is on 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#1835]
Test case 04: E12  Tested on Input version: 2.22.211209063002 IOS, IPAD
- turn on "reuse last value option" in the settings of the testing project input-testing/tc04_recording
- map themes: "Paths and polygons"
- create feature "LineStringLayer" 
- check all 4 checkboxes in features settings (on the right side), feature will be we added 
- now create another feature same as before, except now leave the checkboxes empty, feature won´t be added, no error 
- if you try to add another feature with empty checkboxes, it will be added 
It happens also with the current version of input. 

https://user-images.githubusercontent.com/94351263/145450407-edaf8399-fa2a-4669-b5b1-e26c87c22cba.MP4

**Comment by jozef-budac** [comment]
@PatrikMizera   can you please retest on 2.0.0?

**Comment by PatrikMizera** [comment]
It works just fine on 2.0.0 iOS, each line was created without problems
