### ISSUE TITLE
Incomplete translation for Spanish language. 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#1856]
Hardware settings: 
- Main language - Spanish 

translated seems to be everything except the main bottom UI bar, when outside the project. 

Happens on Android 32,64 and also on iOS.
![266350569_317921103519514_6721312535407798694_n](https://user-images.githubusercontent.com/94351263/146391161-8cdf3efb-3aeb-49c0-8dd0-164e7179d4f3.jpg)
![266658327_430804338504037_1728309223582069061_n](https://user-images.githubusercontent.com/94351263/146391168-9ef3ed35-135b-430a-8f97-676d4c68f9e6.jpg)
![266366479_620801839162465_2762265361525206479_n](https://user-images.githubusercontent.com/94351263/146391169-2716b4e6-4acd-4a4c-993f-c1b07d798790.jpg)
![267641619_1001219773761464_8734247883693628090_n](https://user-images.githubusercontent.com/94351263/146391170-58a39738-3ec1-4e4a-af8e-5700ea4574e2.jpg)
 
P.S. tablet didn´t have screenshot function.

**Comment by tomasMizera** [comment]
This should not be happening anymore :)
