### ISSUE TITLE
Line recording interval as distance 

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/input#1919]
Being able to set the line recording interval to be a distance not a time would be extremely helpful. Data capture can be done in a vehicle or on foot so using a time interval produces very different results.

**Comment by waiotahi** [comment]
plus 1

**Comment by waiotahi** [comment]
ability to pause & restart the GPS stream while capturing polyline would also be useful

**Comment by MTrim** [comment]
plus 1

**Comment by gis-meta-geo** [comment]
plus 1 (please)
