### ISSUE TITLE
Default value is not applied for the position variable in the first instance

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#1938]
I have a project with the @position_latitude @position_longitude as defaults for lat and long in the table.
https://public.cloudmergin.com/projects/saber/12-gps-buff

When I try to record a point for the first time, the default values are not applied. I need to edit geometry or add a new point for the values to appear.

**Comment by rjwillson** [comment]
this bug also causes the other variables not to be filled out

**Comment by saberraz** [comment]
A project to test can be found here:
https://app.merginmaps.com/projects/saber/gps_defaults
