### ISSUE TITLE
problem importing photos from the android device gallery

### ISSUE THREAD

**Issue by marcuzz0** [MerginMaps/input#2005]
Hi,
I have a problem with an android device when I import photos from the gallery.
If I take a photo it is correctly displayed, while if I upload it from the gallery it returns me:

"the image is not available: / image.jpg"

i checked the paths from the qgis project and everything is correct:

@project_folder + '/media'

in fact on another android device everything works correctly.
Some idea?

PS currently i have beta version 1.3.0

**Comment by PeterPetrik** [comment]
related to https://github.com/lutraconsulting/input/issues/655

**Comment by saberraz** [comment]
I think this is a separate issue

https://user-images.githubusercontent.com/2649047/161203838-e06e6b43-5708-4be0-9570-b5f92f01a67c.mov

.

**Comment by erpas** [comment]
A user reports problem with adding an image from gallery on their Android 10 mobile.

I can confirm it as well on my Redmi Note 8 (Android 10) 

![obraz](https://user-images.githubusercontent.com/3106699/186408433-418097dc-9521-448a-87c9-1533de56f248.png)

All the permissions for MM Input are granted.

**Comment by tomasMizera** [comment]
Do we have a project to test this with?

**Comment by bastooo** [comment]
I do have the same problem. For me it is failing all the time. So I guess there is no special case to test.

**Comment by dracic** [comment]
Same problem, but not all devices. So @tomasMizera I think this is Android related issue. For example:

Poco X3:

![photo_2022-12-08_10-50-05](https://user-images.githubusercontent.com/4533263/206415515-b0dd3efd-1599-4c40-bac3-31a4bc54dea3.jpg)

Xiaomi Mi 9T Pro:

![photo_2022-12-08_10-50-20](https://user-images.githubusercontent.com/4533263/206415826-247cb777-1bd5-4cbd-bc15-ff90ca00cb30.jpg)

**Comment by PeterPetrik** [comment]
probably fixed by https://github.com/MerginMaps/input/pull/2834 in release v2.4.0, lets reopen it if the issue persists with 2.4.0 too.
