### ISSUE TITLE
Log window is not readable

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#2041]
When I try to open a project with a missing layer (e.g. https://public.cloudmergin.com/projects/saber/kml_to_delete) Input comes up with an error notification bar. When I click to read more this window will appear:
![image](https://user-images.githubusercontent.com/2649047/162144215-66ec5390-8959-4170-bea4-0e19909e6cd2.png)

The content is not readable. Another side note: would be good if user can select the text for copy and paste.

**Comment by PeterPetrik** [comment]
fixed by https://github.com/MerginMaps/input/pull/2813
