### ISSUE TITLE
Not possible to download My project from Explore

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#2048]
When I try to download My Projects from Explore tab, I get an error that I do not have sufficient permission. We should either not list My Projects under Explore or if we do, we should allow users to download them.

**Comment by PatrikMizera** [comment]
Workspaces update:
now the members can see private WS projects in the explore tab, even if they are currently in different WS

**Comment by tomasMizera** [comment]
Both are hopefully addressed with workspaces, please reopen if not
