### ISSUE TITLE
Photo preview in parent relation feature is broken when photo field is not selected as layer display field

### ISSUE THREAD

**Issue by ekingapex** [MerginMaps/input#2058]
When viewing the form of a parent feature with a 1:N relation with a child layer for associating multiple photograph attachments with the parent feature, Input is only able to display the image preview when the attribute index of the field containing the attachment widget/file path on the child feature is in attribute index 1. If the attribute index for the file path is anything other than 1, the parent feature displays a broken image link icon instead of the photograph. Relationship associations all work properly and the image preview will work correctly in the child feature's form, the issue exists specifically on the parent feature form.

**Comment by saberraz** [comment]
A quick work-around for this could be a plugin configuration to enable/disable the photo preview for each relation.
