### ISSUE TITLE
Project title with special char &

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/input#2059]
it is possible to create a "Test & Trace" project in wizard in Input. But this project cannot sync in merging cloud because the Project name has an '&' in it.

we should forbit too create projects with invalid chars on Input wizard

@varmar05 which chars are forbidden for mergin cloud project name?

**Comment by varmar05** [comment]
we allow to use only alphanumeric or these `-._~()'!*:@,;` characters in the project name

**Comment by tomasMizera** [comment]
Should be fixed now
