### ISSUE TITLE
Conditional visibility is not applied to a group containing a 1-to-many relation

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#2098]
When using drag-n-drop form and having a group which contains a 1-to-many relation, Input ignores the conditional visibility and displays it all the time:
![image](https://user-images.githubusercontent.com/2649047/168030721-babf1d8f-135f-4673-9670-1ce3b6baa03d.png)

You can see this project for the issue:
AndyWalsh/WMBaRv2forLutra

**Comment by geomondego** [comment]
This behavior persists. Any plans to solve the situation?

**Comment by PeterPetrik** [comment]
related/duplicate of #2712
