### ISSUE TITLE
Input does not recognise Grid Shift files in tif format 

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#2105]
I am trying to use a tif file for Grid Shift File but Input does not recognise it and only allows gsb format.

**Comment by saberraz** [comment]
The project using TIFs are taking more than 10 times to load and the app is almost unusable.

**Comment by wonder-sk** [comment]
Related ticket that would switch from gsb format for grid shift files to tif: https://github.com/MerginMaps/input-sdk/issues/58

**Comment by saberraz** [comment]
In addition to slow loading of the project, there is also a crash immediately after user downloads the project and tries to open it. Subsequent opening works without crash (but takes ages).
