### ISSUE TITLE
Unable to see "complete purchase" button, when buying subscription via Android or iOS 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#2120]
Fill out the subscription form on either iOS or Android and: 
for iOS you cannot see the button, it is hidden under the bottom strip. You can "hard scroll down" but even that won´t help. 

https://user-images.githubusercontent.com/94351263/173025414-b1f6d0a5-6778-4dd4-8d37-23457680e4f0.MP4

for Android, you see a slight sliver of the button, so if you try enough you will be able to press it and the process will go on without failure. Here, you cannot slide it more down as with iPhone. 

![Screenshot_2022-06-10-10-08-38-588_com android chrome (1)](https://user-images.githubusercontent.com/94351263/173026378-521a4488-09ce-4bff-bef9-3e4e5d475dc9.jpg)

Both on the actual merginmaps.com web and with latest iOS and Android versions

**Comment by PeterPetrik** [comment]
this is problem on webapp.
