### ISSUE TITLE
Android build Fails  due to empty MERGINSECRETS_DECRYPT_KEY 

### ISSUE THREAD

**Issue by islam500** [MerginMaps/input#2124]
Can not build android workflow on github because of the missing I dont know the password for the encrypted merginsecrets.cpp
I have the MERGINSECRETS_DECRYPT_KEY setup but dont know what to put inside.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/2852014/173794071-677204f3-e836-43fb-a548-54d209111530.png">

**Comment by tomasMizera** [comment]
Hi @islam500, you can skip the step `Extract Mergin API_KEY` altogether. It is a security thing for our servers, you will be able to use the app without it.

**Comment by islam500** [comment]
Thank you for the clarification.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tomasMizera** [comment]
The only thing to note is that you will not be able to register a new account on our public server `https://app.merginmaps.com/`.

**Comment by islam500** [comment]
That’s good to know

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
