### ISSUE TITLE
Snapping - does not record the same coordinates

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/input#2130]
I created a feature in Input with snapping, synced to QGIS and then compared if the snapped vertex is the same as the one it snapped to. Turns out that for some (not all) vertices coordinate values differ a little.

<img width="1135" alt="image (1)" src="https://user-images.githubusercontent.com/22449698/175327207-cc4ce593-1bd8-4412-a4e7-205d4711c6d4.png">

**Comment by alexbruy** [comment]
I can't reproduce this using my phone and with Linux build. Might be related to hidpi screens.

**Comment by tomasMizera** [comment]
@jozef-budac

**Comment by jozef-budac** [comment]
Can be related to this:
https://lutraconsulting.slack.com/files/U01T1L12335/F03MDHEN6AV/image_from_ios.mp4

**Comment by jozef-budac** [comment]
I tried this scenario, in input on Android I created a polygon with 5 points.
Then I created 2nd same polygon, but with snapping tool with exact same 5 points as first one.

This are the coordinates of first polygon:

Polygon ((17.04835226784347668 48.1988806214264045, 17.0474370366437995 48.19901134511145813, 17.04755144054376359 48.19964317155354649, 17.04836861125776082 48.19974121288925062, 17.04890794392900233 48.19931636574605704, 17.04835226784347668 48.1988806214264045))

This are the coordinates of second polygon

Polygon ((17.04835226784347668 48.19888062142638319, 17.0474370366437995 48.19901134511145813, 17.04755144054376359 48.19964317155352518, 17.04836861125776082 48.19974121288925062, 17.04890794392900233 48.19931636574604994, 17.04835226784347668 48.19888062142638319))

There are small differences there
