### ISSUE TITLE
Unpredictable but regular forced log Out from Mergin on Android Mobile Devices

### ISSUE THREAD

**Issue by rjwillson** [MerginMaps/input#2139]
My android phones and tablets are regularly (i.e., every 2 or 3 days) logged out from Mergin Maps. It doesn't seem to matter whether the device is on cellular or wifi. Mergin will say it has something to do with the connection but in many cases the connection is just fine. Even if there is a problem with connection the device should not be logged out once a better connection is found.

As a workaround I have put the username and passwords for each device on the home screens of the devices that staff use so that they can copy and paste them and log back in. However, the logout happens too regularly and so staff resort to poor passwords and this has become my #1 support call from staff (i.e., the tablet is logged out again). Seems to be multiple versions of Android. Not sure if this happens on iOS

**Comment by TrueBabyStar** [comment]
I have the same problem. My staff work in the field, often without data reception. It is sometimes not possible to log back in. Is there any way to ensure that Mergin Maps does not log out?

**Comment by HugoP27** [comment]
We have the same issue and are experiencing it more and more. A lot of people also report being logged out while in the field with zero signal and being unable to login again, this means that they cannot use the app until they get back to an office and login again. This is causing a lot of frustration from our clients and consultants and we are willing to contribute toward fixing the issue if possible please @saberraz 

The app used to be logged in permanently (or so it felt) which was great for users, its only the past few months that this issue started.

**Comment by tomasMizera** [comment]
Hello @HugoP27 and others, thanks for reporting this issue again. We had hard times trying to simulate it on our infrastructure. Do you maybe have a set of steps that we could follow that would end up being logged out?

**Comment by HugoP27** [comment]
Hi @tomasMizera no formal steps to reproduce unfortunately, the only constant is that it happens in areas with very poor signal. So in areas with constant signal it works fine and areas with no signal it works fine, but as soon as you are in an area with poor signal that comes and goes, it logs out.

**Comment by PeterPetrik** [comment]
@rjwillson @HugoP27 https://github.com/MerginMaps/input/pull/2721 should fix the issue

**Comment by tomasMizera** [comment]
Hi all, this issue should be fixed already (https://github.com/MerginMaps/input/pull/2721)
