### ISSUE TITLE
Can't split polygon with crossed lines

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2154]
If there is a polygon with lines crossing each other, I can't split it.
I marked this as a bug, as this should work from my point of view

https://user-images.githubusercontent.com/83582181/177476151-ae500ebf-fd39-47c1-8326-bfc04ecfde30.mp4

**Comment by tomasMizera** [comment]
You have an invalid geometry, it is the same behaviour as in QGIS.

**Comment by jozef-budac** [comment]
Yes, I verified that QGIS behaves the same
