### ISSUE TITLE
Line feature with crossed line is splited to wrong number of features

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2155]
When I split line with crossed lines, and I split one line of it, it is splinted to 4 features.
Expectation would be to spit it to just 2 features.

https://user-images.githubusercontent.com/83582181/177476861-89f4d5f2-6a39-40df-a302-1202e60abc92.mp4

**Comment by tomasMizera** [comment]
Best to double check with QGIS, it most probably does the same thing

**Comment by jozef-budac** [comment]
I verified that QGIS behaves the same

**Comment by PeterPetrik** [comment]
input-idk is on final-3_32_1, so this one should be already fixed? @jozef-budac
