### ISSUE TITLE
Features are displayed on wrong place on the map

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2161]
for project https://app.merginmaps.com/projects/tin1/tc04_recording_clone/tree
all features are recorded in Slovakia, but in input on Windows, there are located somewhere near Svalbard

<img width="1221" alt="Capture3" src="https://user-images.githubusercontent.com/83582181/177498028-2910e5c9-4636-4e56-884a-102ee943a432.PNG">

**Comment by tomasMizera** [comment]
Due to #2178

**Comment by tomasMizera** [comment]
Should be fixed now
