### ISSUE TITLE
Crash when opening a second project with WMS layer

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/input#2183]
I am getting a crash on both Android and Linux when I first open a project and then open another project. Normally this works fine, but with these two projects I am getting crash all the time:
1. start Input
2. open `saber/null_issue` project
2. open `support/grid_shift_with_tif` project

A quick look with debugger suggests that ActiveProject::load() triggers reading of the project, which contains a WMS layer, which in turn tries to fetch server capabilities and calls the dreaded QEventLoop::exec() to wait for the response. The event loop also starts to process some QML events and ends up calling ActiveLayer::name() which apparently tries to access a map layer that has been destroyed. Probably it would help to:

1. make sure that we reset ActiveLayer before loading a project
3. use QPointer in ActiveLayer so that we never end up with a dangling pointer.

**Comment by tomasMizera** [comment]
Hmm, have you used the latest master for this one? I recently moved the active layer reset function above project load: https://github.com/MerginMaps/input/pull/2164/files#diff-dff7df13679393bb5d0d50f013ac1087c67133100775226ef54f6f6423fe7833R153

**Comment by wonder-sk** [comment]
Ahh good point! I have used 1.6.0, I thought that fix already went to 1.6.0, but I can see now it's only on master. Just checked again on Linux and the crash is gone on master - well done :-)

Fixed by #2164
