### ISSUE TITLE
Projects not sorted/loaded alphabetically 

### ISSUE THREAD

**Issue by chris9404** [MerginMaps/input#2196]
I have about 250 projects in the Shared With Me tab.
This in itself is not a problem, but on first load a bunch of projects load and are displayed alphabetically. 
I have a video below where I want to open the agmc/Excelsior project as an example:

https://user-images.githubusercontent.com/85164641/183023049-a94d0d4d-5214-4082-99e8-adfb5e608105.mp4

What I would expect is to find agmc/Excelsior immediately, as it starts with 'E' and there are a bunch of projects in the list with letters F - Z, but it only shows after multiple pagination loads. Because of this the user will on first look think they don't have access agmc/Excelsior.

This problem, in conjunction with the search function being glitchy (https://github.com/MerginMaps/input/issues/1714) makes the Shared with Me tab a bit difficult to work with at times.

**Comment by jozef-budac** [comment]
related to https://github.com/MerginMaps/input/issues/2196

**Comment by tomasMizera** [comment]
This should no longer be an issue on the latest version. Feel free to reopen if you still struggle with it
