### ISSUE TITLE
Split Geometry button is active on non spatial layer's features

### ISSUE THREAD

**Issue by uclaros** [MerginMaps/input#2227]
On @saberraz 's `foss4g_2022_workshop` project, photos are stored on a geometryless table, but when editing a photo feature the split button is active.

![Screenshot_20220821-160327](https://user-images.githubusercontent.com/11358178/185794848-6701fa7d-25c9-4b33-b489-10e9afe89e9c.png)

![Screenshot_20220821-155837](https://user-images.githubusercontent.com/11358178/185794718-0d26951a-2edc-4850-852c-485c23f1d0ee.png)

![Screenshot_20220821-160256](https://user-images.githubusercontent.com/11358178/185794850-86340c12-5b41-4ee3-99f5-796a7900792a.png)

**Comment by tomasMizera** [comment]
Thanks @uclaros ! Will be fixed when #2228 gets to master
