### ISSUE TITLE
Different name for button

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2232]
There are two names for button which add point to the geometry. It is sometimes "Add" and sometimes "Release" in the same scenario. 

For example, when you add point to the end to the line string, it the name is "Add", but when you remove the point it is changed to "Release", then when to add point, it is changed back to "Add" 

I think it should be the same. 

https://user-images.githubusercontent.com/83582181/187130629-ac05503c-a4fe-4268-8ab3-f492ed51c93e.mp4

**Comment by tomasMizera** [comment]
It is part of design, but we might want to rethink that 🙂

**Comment by jozef-budac** [comment]
It was by design even for the same state? I understand that in different states there are different names.. like I am holding a point I want to release it and not add. But in the case described in this scenario, I am not holding any point, I am adding it and still there is a release name for the button

**Comment by tomasMizera** [comment]
You are actually releasing, not adding. When you hit remove during recording, last existing point is selected.
