### ISSUE TITLE
Feature is not redraw after cancel

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2233]
When I cancel editing or redrawing, the feature is not re rendered to its previous (original) state. I need to move map to see the original state.

Scenario:
1) edit a line feature
2) add some point into it
3) then hit cancel, edit page appears and hit cancel again

On map canvas you can see feature with all the points added. When you move the map, the feature will rerender to its original state.

Expectation is, that after cancel of the editing, the feature will be in original state immediately.

https://user-images.githubusercontent.com/83582181/187130848-7f35e9bc-d076-40e2-a28a-4d227d2e0a9d.mp4

**Comment by alexbruy** [comment]
Should be fixed with #2250

**Comment by jozef-budac** [comment]
Yes, this issue is fixed in the latest build
