### ISSUE TITLE
3 points needed for linestring

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2234]
When I try to save linestring feature with 1 point, I get notification, that 3 points are needed.
Actually only 2 points are needed. It would be good to change the number in the notification from 3 to 2.

![image](https://user-images.githubusercontent.com/83582181/187132597-4ce76d5b-83c6-4869-85a4-ba4e747fb248.png)

**Comment by alexbruy** [comment]
Should be fixed in #2250

**Comment by jozef-budac** [comment]
Yes, it is fixed in latest build
