### ISSUE TITLE
Multiple points recored by itself

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2237]
This is really strange bug which happens to me once. I was not able to reproduce it, but it is so strange, that I would like us to know about it. 

I am not able to provide the scenario to reproduce it, but check the video to see that happens.

https://user-images.githubusercontent.com/83582181/187140362-29973567-cec9-454f-b557-6ec3786bb512.mp4

**Comment by tomasMizera** [comment]
Could not be reproduced.
