### ISSUE TITLE
Split geometry option is available for points features

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2239]
Split geometry option is available for points features. I would expect, that for pints, splitting is not allowed
Also, both edit and redraw geometry is available for normal point features. They do basically the same thing. I am not sure we want it to have this way.

**Comment by alexbruy** [comment]
Should be fixed in 2250

**Comment by jozef-budac** [comment]
Split geometry option is still there. The change is that it is not clicable

https://user-images.githubusercontent.com/83582181/188828175-1acaa651-8337-4af3-949c-339b4e249a9f.mp4

**Comment by alexbruy** [comment]
So it is not available, right? Should it be hidden?

**Comment by alexbruy** [comment]
It is disabled, probably this is platform-specific that UI does not reflect that.

**Comment by tomasMizera** [comment]
Yep, let's hide it for points, we will never support splitting of points 🙂

**Comment by jozef-budac** [comment]
We are almost there :D I would like the background to be only behind redraw button

![image](https://user-images.githubusercontent.com/83582181/189622115-962f9471-584f-46e4-941b-87387137ba6b.png)
