### ISSUE TITLE
Can't add new point in edit geometry for multipoint feature

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2240]
When I try to edit multipoint feature, add button is disabled, so I can't add new point to the feature.
When I use redraw function, I can add multiple points in multipoint feature. 

Expectation is, that in edit mode, I can add new points with add button.

**Comment by tomasMizera** [comment]
Is this still valid? I believe not with the latest #2256  :)

**Comment by jozef-budac** [comment]
Yes, it is fixed in latest change.
