### ISSUE TITLE
Can't remove part of multipolygon layer

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2243]
Scenario:
1) have multipolygon feature with 3 parts (3 polygon i one feature)
2) hit edit the feature
3) remove all point from one part and hit save
-> we get notification, that at least 3 points are needed for a feature

Expectation is, that one part of the feature will be removed.

https://user-images.githubusercontent.com/83582181/187158970-e4de6712-6267-41b0-b6b9-23b1b7bb09e4.mp4

**Comment by alexbruy** [comment]
Should be fixed in #2250

**Comment by jozef-budac** [comment]
Fixed in latest version
