### ISSUE TITLE
Edit gemometry is available for nongeo features

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2264]
Edit geometry feature is available for nogeo features also. The button should not be there.

https://user-images.githubusercontent.com/83582181/189635334-352bc060-e45d-404c-a91e-9d40e4738308.mp4

**Comment by jozef-budac** [comment]
There is also crash, as clicking edit will trigger edit mode on the background


https://user-images.githubusercontent.com/83582181/189636091-a6ba4d25-d326-4879-8c4f-1ffa881208ac.mp4

**Comment by alexbruy** [comment]
Looks like this was true in previous versions as well.

**Comment by jozef-budac** [comment]
Edit geometry button was there but disabled

**Comment by jozef-budac** [comment]
![image](https://user-images.githubusercontent.com/83582181/189642508-1df723ba-2081-4b9d-aa2a-f1b53f64d5b2.png)

**Comment by jozef-budac** [comment]
Fixed in latest version
