### ISSUE TITLE
Password hint is not visible on Android

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/input#2274]
During registration, when a password is not strong enough we show a warning to users and give them a hint of what their password must include.
On Android, we show this in the Toast element. This, however, is not capable of showing such a long message (at least from >Android 12),. 
As a result, users do not really know what are the password constraints.

Moreover, on Herman's phone it only said "Password is not strong enough.".

<table>
<tr>
<th>
iOS
</th>
<th>
Android
</th>
</tr>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/22449698/190151412-bc233e4f-b21b-486d-9984-a020d4fe7e8e.jpeg" width=300>
</td>
<td>
<img src="https://user-images.githubusercontent.com/22449698/190150719-c1bde17f-c7da-4263-8ccd-f12ecf37cac7.jpg" width=300>
</td>
</tr>
</table>

**Comment by jozef-budac** [comment]
same problem as: https://github.com/MerginMaps/input/issues/1680

**Comment by tomasMizera** [comment]
Not really the same, but might be related 🙂

**Comment by iiLubos** [comment]
Toast/popup notification replaced by Error messages under the related field.
Pool request: https://github.com/MerginMaps/input/pull/2699/

**Comment by PeterPetrik** [comment]
fixed already
