### ISSUE TITLE
Different exifdata between iOS and plugin 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#2295]
Project: TC04_recording

1. Set a photo theme 
2. record a feature and take a picture **horizontally**
3. record another feature and take a picture at 45° degrees 
4. compare the **direction** (the first one in Input) between iPhone and QGIS plugin
5. It will be different 
6. Other fields should be correct, even direction_raw  

Input 1.8.0+
iOS version: 15.7

**Comment by jozef-budac** [comment]
I can't replicate this, We need to check with Patrik about this

**Comment by tomasMizera** [comment]
Is this one still reproducible?

**Comment by PatrikMizera** [comment]
it is still broken and I also updated the ticket

**Comment by jozef-budac** [comment]
@PatrikMizera, can you reproduce this on production? If yes, please change label to "bug"

**Comment by PatrikMizera** [comment]
just tested it on 1.9.0. and it did not occur
