### ISSUE TITLE
Position variables are not working

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#2296]
While testing on project tc05_position_variables, iPhone was unable to fill out the positional variables. 

Input 1.8.0 
iOS: 15.7

**Comment by saberraz** [comment]
Is it related to https://github.com/MerginMaps/input/issues/1938?

**Comment by PatrikMizera** [comment]
It is, but now it will not fill out, even after the first try.

**Comment by tomasMizera** [comment]
Isn't it the same as https://github.com/MerginMaps/input/issues/1836? Is it when you take a picture or choose one from gallery?

**Comment by PatrikMizera** [comment]
No, this is without taking pictures or choosing from gallery

**Comment by tomasMizera** [comment]
Hmm, it is even worse, it is not working for some time now. It does not work even on Android

**Comment by jozef-budac** [comment]
It is fixed in https://github.com/MerginMaps/input/pull/2297
