### ISSUE TITLE
Adding measurement tool on app canvas - Feature request

### ISSUE THREAD

**Issue by PCA-Geodata** [MerginMaps/input#2302]
Hi Lutra Team, 

I would like to ask if could be possible to add a simple measurement tool to the app's main canvas. 
It would be a very useful tool for many users. 

If possible, I am interested in development costs and I can consider the possibility to sponsor it. 

Thanks

**Comment by saberraz** [comment]
Hi @PCA-Geodata could you please drop us an email on info@lutraconsulting.co.uk and we can provide you more details.

**Comment by saberraz** [comment]
Duplicate of https://github.com/MerginMaps/input/issues/1400
I am closing this in favor the above ticket which has more info about how the tool should look like.
