### ISSUE TITLE
brokend data providers on Android 32 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#2306]
tc_06_format_wfs , the project is showing nothing.
tc_06_online_cog, both themes are showing black screen

Input: 1.8.0. Android 32

**Comment by tomasMizera** [comment]
Is this still reproducible?

**Comment by PatrikMizera** [comment]
TC06_online_cog is working 
TC06_format_wfs can not be tested, because a new bug has been found, you are unable to close pop-up windows 
https://github.com/MerginMaps/input/issues/2395

**Comment by jozef-budac** [comment]
@PatrikMizera please check, if this is reproducible on current version on google play/apple store, and update the label to "bug".

**Comment by PeterPetrik** [comment]
Tested on 32b Samsung galaxy tab 2 (android 7) from build https://github.com/MerginMaps/input/pull/2703 
-TC06_online_cog works 
- I am not able to test TC06_format_wfs for missing proj files
