### ISSUE TITLE
IOS attachment value not applying custom folder paths

### ISSUE THREAD

**Issue by stevenjh** [MerginMaps/input#2353]
I have a photo attachment setup as pictured:
![image](https://user-images.githubusercontent.com/1258872/198899156-f61133e5-93d8-41fe-a967-a3424e27f8fb.png)

For android users it is working as expected creating the attachment value of `rain-garden-images/<photo_name>.jpg`
For IOS users it is not prepending the custom folder, creating an attachment value of `<photo_name>.jpg`

The IOS user is taking the photos from within the MerginMap app and was using either release 1.8 or 1.9

**Comment by stevenjh** [comment]
A user in Slack channel noted:

> I noted this. Try using '||' to concatenate instead of '+'. Maybe I'm missing something, but in my case '+' works only in QGIS, '||' works both in Mergin and QGIS.

I've updated our app and tested in Android, it continues to work there and will await our IOS user testing.

**Comment by bastooo** [comment]
Having the same issue on iOS version 2.1.0. Please fix it.

**Comment by stevenjh** [comment]
Hi @saberraz,  is there going to be a fix on this or should we get in the habit of not using the photo folder function?  Thanks!

**Comment by jozef-budac** [comment]
@iiLubos patch seems to fix this problem
