### ISSUE TITLE
No warning shown if project has no CRS set

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/input#2362]
for my project (peter.petrik/LutraTeam) - web mercator, GPS panel shows log/lat (16, 36.323; 49, 12.536), but zoom on GPS position throws me to 0,0. Also the orange circle is in top right corner and sight cone is displaced too. Also the scalebar is screwed-

I see a bunch of errors in log 
`Internal GPS provider: Error occurred (position source) code: 4`

![IMG_4E76E5573C23-1](https://user-images.githubusercontent.com/804608/200270445-18832d17-79b7-444c-a884-90776df8b77a.jpeg)

OK, I downloaded another projects and switching between projects and now the cone + point is on the 0,0 location (not in corner). But position is still somewhere in Africa 

![IMG_F4EA73B684CB-1](https://user-images.githubusercontent.com/804608/200271801-c99b496d-5372-4207-b2f6-c125ba456c70.jpeg)

interestingly for project peter.petrik/test it works all fine. Maybe it is PROJ issue?

iPhone SE 2020, Input 2.0.0 (22.11.357611), iOS 15.6, clean build

**Comment by PeterPetrik** [comment]
Hmm, now it works - it looks like I have canvas projection setup to "no-projection" and it made this mess.

**Comment by PatrikMizera** [comment]
I have the same problem on Android 11 with only project tc02_digitizing
![Screenshot_2022-11-07-10-28-06-855_uk co lutraconsulting](https://user-images.githubusercontent.com/94351263/200276191-0d41b907-dcd4-4f5c-bce2-45869be27afd.jpg)

**Comment by wonder-sk** [comment]
I can replicate the issue with v16 of the project, when the project has no CRS set. We should probably issue validation warnings in MM plugin so that people do not create projects with no CRS set, as this will lead to lots of problems anyway - all proper survey projects should have CRS set...

**Comment by wonder-sk** [comment]
Related MM plugin ticket: https://github.com/MerginMaps/qgis-mergin-plugin/issues/470

It would make sense to have a warning about no CRS upon project load in Input as well, but addressing this one in Input is low priority I guess...
