### ISSUE TITLE
QT6: value relations doesn't work

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2412]
With QT6, value relations doesn't work. After I chose value from relation, nothing is used in the form

https://user-images.githubusercontent.com/83582181/204779876-1412ae4c-cb09-45eb-986a-6deb658100df.mp4

**Comment by wonder-sk** [comment]
Also seen this - I _think_ in order to replicate this, one needs to record a feature in one layer with value relation field, then switch to another layer with value relation field...

**Comment by tomasMizera** [comment]
Which project is this @jozef-budac please?

**Comment by jozef-budac** [comment]
it is input-testing/tc05_forms_widgets

**Comment by jozef-budac** [comment]
Verified on current master
