### ISSUE TITLE
QT6: Input crashes when camera permission is not granted

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2432]
Scenario:
1) open project with picture attachment (input doesn't have permission for camera)
2) in the form hit camera and do not grant permission for it
-> input crashes

https://user-images.githubusercontent.com/83582181/205590066-d1ea7dc0-5fc8-4052-a60a-ffcb0e037f9f.mp4

**Comment by jozef-budac** [comment]
Verified in PR

**Comment by alexbruy** [comment]
Fixed by #2456
