### ISSUE TITLE
Wrong formatting of project loading error snackbar

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2435]
The formatting of missing layer dialog is quite strange. IT would be better to polish it

![image](https://user-images.githubusercontent.com/83582181/205595936-df4b52fc-0205-4435-b772-164fc52b6cf0.png)

**Comment by jozef-budac** [comment]
I believe you can get this error, when you remove gpkg file with layer, which is used in the project. I don't have specific project for this. But if you need it, I can create one

**Comment by tomasMizera** [comment]
I saw this on public version too :)

**Comment by jozef-budac** [comment]
Duplicate of https://github.com/MerginMaps/input/issues/2435
