### ISSUE TITLE
Qt6: toolbar behind navigation bar

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/input#2439]
On Android, when using "Swipe gestures" navigation instead of "Buttons" navigation, the toolbar of Input gets behind it:

<img src="https://user-images.githubusercontent.com/193367/205607755-6ab4c14c-d8a6-48d4-8702-b968889f0a5b.jpg" width=350>

**Comment by tomasMizera** [comment]
Source of the issue https://bugreports.qt.io/browse/QTBUG-96877
