### ISSUE TITLE
QT6: editing of linestring 

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2441]
Scenario:
1) open project https://app.merginmaps.com/projects/input-testing/tc16_geometry_editing/tree
2) create a line string with multiple pints and save
3) then hit edit geometry for it and try to remove all points
-> you can remove just one one two points -> 1st error

4) after hitting multiple times the remove and add point you are not able to add point to the end of the string -> 2nd error

https://user-images.githubusercontent.com/83582181/205616851-489eb957-eae2-46e6-9e30-44b31c058a96.mp4

**Comment by tomasMizera** [comment]
Related to #2446

**Comment by jozef-budac** [comment]
I retest it on the today's latest master and it looks like, it is the problem with multiple click on the same button.
When I hitting buttons very slowly, the issue is not observed. But when I hit for example add button multiple times, the buttons stops working. 
Same for Undo button, or remove button

**Comment by tomasMizera** [comment]
Should be fixed now in #2463 . @jozef-budac reopen this one if it is not fixed
