### ISSUE TITLE
Input will become extremely slow or nonresponsive while recording or editing line/polygon 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#2446]
1. any project with lines and polygons 
2. start recording lines/polygons 
3. you can record the first 2 points without issues 
4. after that, the app will become very slow to record or will not record at all 
5. you can still save the feature 

iPhone: 11; iOS: 16.1.1.

(I am constantly pressing the record button)
https://user-images.githubusercontent.com/94351263/205653576-a7a0f5ce-b7ef-4cd3-acd7-373bfee849c7.mp4

**Comment by tomasMizera** [comment]
@PatrikMizera Can you please pass me the project?

**Comment by tomasMizera** [comment]
Should be fixed now with #2463
