### ISSUE TITLE
QT6: Unable to exit stake out after opening GPS info

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/input#2457]
Steps to reproduce:
1. open a project, pick a point, start stake out
2. tap on the GPS accuracy label - it will open GPS info page
3. close the GPS info page
4. now it is impossible to exit stake out (using Android's back button nor X button) - one needs to restart the app

When not going into the GPS info page, everything works fine.

**Comment by alexbruy** [comment]
Looks like duplicate of #2438

**Comment by tomasMizera** [comment]
Yep, closing in favor of #2438 - duplicate
