### ISSUE TITLE
Qt6: in landscape mode, some part of the window is hidden behind android buttons 

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2469]
Check right side of the screenshot

![image](https://user-images.githubusercontent.com/83582181/208058322-c8c71660-1bfa-419b-b295-e9727ebb2025.png)

**Comment by tomasMizera** [comment]
Another effect of https://github.com/MerginMaps/input/issues/2439, closing this one in favor of the mentioned ticket
