### ISSUE TITLE
QT6: tab sliding doesn't work

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2473]
When you have tabs in the form, previously you could swipe left and right through it. Right now it is not possible and you have to use clicking to tabs

**Comment by tomasMizera** [comment]
Yep, this will be a known issue until Qt fixes the bug https://bugreports.qt.io/browse/QTBUG-109124

**Comment by tomasMizera** [comment]
See more info here https://github.com/MerginMaps/input/pull/2423
