### ISSUE TITLE
QT6 iOS: decimal dot bug

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#2474]
1) project e.g. tc05_forms_derived 
2) record a feature 
3) fill in some numbers then try to put in a dot, you have to press it 3 times and then it will vaporize your last digit 
4) comma can not even be typed in 

iOS: 16.1.1 iPhone 11, Input 2.0.0

https://user-images.githubusercontent.com/94351263/208084697-ebde8fdc-d4ce-4b50-8371-5542756a6db9.MP4

**Comment by tomasMizera** [comment]
3 dots -> iOS feature, it is a special character you can insert by hitting the dot character three times in a row https://discussions.apple.com/thread/5526395 It is called "Smart Punctuation"
