### ISSUE TITLE
gps not updating in expressions 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#2477]
tc05_expression_tickets

1) record a feature in the Ticket_1756 layer 
2) when changing geometry, the fields are not updated

**Comment by jozef-budac** [comment]
I believe here is problem in TC. The issue was, that the form was empty. If the form is filled, the issue should be solved.
The new data will be uploaded when GPS coordinates will be changed (by Location changer app or moving somewhere else)
