### ISSUE TITLE
redraw functionality is missing in some projects in Android  

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#2480]
project tc16_geometry_editing is not showing the possibility to redraw features

**Comment by tomasMizera** [comment]
Hmm, a few issues here:
 - I can't find the project `tc16_...`, did you mean `tc04_geometry_editing`?
 - I can not reproduce this issue on the tc04 project
 - Are you sure you tested it on **existing** features? This option is not available on features that you just created (those that are not saved yet)

**Comment by tomasMizera** [comment]
Please reopen the ticket if any of the mentioned points are not correct and add more information + screencast.
