### ISSUE TITLE
Mobile App - Shared Project Limit and Organization Project Sharing Issue

### ISSUE THREAD

**Issue by ekingapex** [MerginMaps/input#2482]
We have identified an issue within the mobile app for displaying/searching for projects after a certain number of shared projects occurs. I cannot determine the exact number, but it appears to be around 445 projects; once you have more than whatever that number may be shared with you, you can no longer search or find new projects in the mobile app. This is a limitation that needs to be addressed, but it is also tied to a separate issue that affects all aspects of Merginmap (mobile app, web interface, and QGIS plugin). If you are a member of an organization, ALL projects in that organization are counted as shared projects for you, regardless of whether or not you are assigned as a user on the projects. This should be changed so that only projects you are actually assigned to are considered projects shared with you, with an exception of "owner" and "admin" level users of the organization.

This is a major issue for our users at this time and we are having to remove users from the organization just to allow them to pull up projects in the mobile app.

**Comment by tomasMizera** [comment]
Hello @ekingapex, we are in the process of migrating to workspaces. It should ease working with previous organisations and give you a better experience when working on the phone. From now on, you will be able to switch between workspaces and see all projects from that workspace (your organisation will become a workspace). 
You can read more here: https://merginmaps.com/blog/introducing-workspaces-simplified-collaboration 

Please make sure you update your mobile app and QGIS plugin to the latest versions in order to get all the benefits of using workspaces (mobile version 2.0.0 and higher and plugin 2023.1 and higher)

We will double-check the issue about showing a maximum of 445 projects and get back to you. Although, I would highly recommend using the search bar in case of that many projects.

**Comment by ekingapex** [comment]
Thanks Thomas! Just for clarification about the search portion; with the issue we were seeing, projects that did not show up in the project list due to the maximum also could not be found with the search bar in the app, it would just return a “no projects found” message.

We’ve since added additional organizations/workspaces and divided the projects out to avoid the issue, but I will follow up if we run into the issue again down the road with the new workspaces change.

Thank you for your time,
Evan King
Royal Treasury Enterprises, LLC on behalf of Apex Advanced Technology
770-601-7665

**Comment by ekingapex** [comment]
I have verified that the issue is still present with the workspaces change. I am currently an admin on three different workspaces, each of which has 200-300 projects. I am able to search recently created projects in any of the workspaces and view the entire list on the web portal and in the QGIS plugin with no issue, but if I search for a recently added project within any of the workspaces in the mobile app, I get a “no projects found” return. I can still see and search older projects in the mobile app with no issue, but ones added after that cutoff (which appears to be somewhere around 445, I am not able to verify the exact number) I am unable to access.

If you would like me to post an update on this to the GitHub ticket or in the Slack, please let me know.

Thank you for your time,
Evan King
Royal Treasury Enterprises, LLC on behalf of Apex Advanced Technology
770-601-7665

**Comment by ekingapex** [comment]
We will discuss this in detail during the daily standup at 4:30pm today.

Thomas


From: Evan King ***@***.***>
Sent: Tuesday, February 7, 2023 1:46 PM
To: MerginMaps/input ***@***.***>; MerginMaps/input ***@***.***>
Cc: Mention ***@***.***>; Thomas Yuen ***@***.***>
Subject: RE: [MerginMaps/input] Mobile App - Shared Project Limit and Organization Project Sharing Issue (Issue #2482)

I have verified that the issue is still present with the workspaces change. I am currently an admin on three different workspaces, each of which has 200-300 projects. I am able to search recently created projects in any of the workspaces and view the entire list on the web portal and in the QGIS plugin with no issue, but if I search for a recently added project within any of the workspaces in the mobile app, I get a "no projects found" return. I can still see and search older projects in the mobile app with no issue, but ones added after that cutoff (which appears to be somewhere around 445, I am not able to verify the exact number) I am unable to access.

If you would like me to post an update on this to the GitHub ticket or in the Slack, please let me know.

Thank you for your time,
Evan King
Royal Treasury Enterprises, LLC on behalf of Apex Advanced Technology
770-601-7665

**Comment by tomasMizera** [comment]
Hello @ekingapex , the issue should be fixed now, let me know if you still fight with this.
