### ISSUE TITLE
styling of subscription panel

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/input#2485]
- unable to scroll
- The text is over the rest of the bullet points

![IMG_3007](https://user-images.githubusercontent.com/804608/210234594-2651c0cc-1776-484c-881d-4104599e3457.PNG)
 
--------

![IMG_3005](https://user-images.githubusercontent.com/804608/210234603-dbec1416-7eae-4402-b4e7-18ea4ef8aef1.PNG)

**Comment by tomasMizera** [comment]
This is fixed now with workspaces
