### ISSUE TITLE
QR code doesn't populate field, if the value is not valid

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2498]
Scenario
1) open project https://app.merginmaps.com/projects/input-testing/tc04_qrcode/tree
2) hit add to record a feature wit
3) in the form try to use QR code reader to read num field (num_qrcode).
If the QR code contains long number, or it contains non numeric character, it closes and no value is inserted into the field.

Expectation is that the value will be inserted, but validation error will occurs. As least this was previous behavior. But probably this is not a blocker

**Comment by tomasMizera** [comment]
This is another result of https://github.com/MerginMaps/input/issues/2496 . I will close this one as it will be fixed by the mentioned ticket. We need to test this though, thanks for reporting.
