### ISSUE TITLE
Zoom in on photos

### ISSUE THREAD

**Issue by AndyWalsh1** [MerginMaps/input#2512]
Currently when you open photos in Input it is not possible to zoom in and move around the image. It would be useful if ‘pinch to zoom’ was enabled.

**Comment by tomasMizera** [comment]
Hi @AndyWalsh1, thanks for your feedback! 
We indeed plan to add this feature later in the year. If you'd be interested in helping us fund it, let us know at sales@merginmaps.com

**Comment by PeterPetrik** [comment]
fixed by https://github.com/MerginMaps/input/pull/2715
