### ISSUE TITLE
32 bit version Available???

### ISSUE THREAD

**Issue by 29Sheriff** [MerginMaps/input#2529]
Is there a version for 32 bit systems? if so could you point me toi it. I tried versions 1.8.1 and 1.6.0 because their titles don't include a 'win64' but all I got after the installation was "this software can't run on your version of windows". I am running windows 8.1 on a Dell Venue 8 tablet

**Comment by tomasMizera** [comment]
Hello @29Sheriff,
we have a 32-bit version of our app only on Android. As for windows, we currently offer only the 64-bit version.
