### ISSUE TITLE
Map sync button selects feature behind the button

### ISSUE THREAD

**Issue by Hackster93** [MerginMaps/input#2549]
When clicking the sync button in the map window, the feature behind the button gets selected as well. See the attached video.

Android running version 2.0.1.

https://user-images.githubusercontent.com/90187049/217281957-283b3940-8df9-406a-86c4-334ad552ac96.mp4

**Comment by tomasMizera** [comment]
Hello Chris @Hackster93, thanks for reporting the issue.
@alexbruy it is yet another occurrence of https://github.com/MerginMaps/input/commit/a052966715bb676e707fddc2a00d5304e14b942e and https://github.com/MerginMaps/input/pull/2425

**Comment by Tadeo98** [comment]
I can confirm. Can be pretty annoying when the map window is situated within a large polygon and with each sync the feature gets selected and centered on the map.
