### ISSUE TITLE
Input crashes when form contains non-existent relation

### ISSUE THREAD

**Issue by alexbruy** [MerginMaps/input#2569]
Subject says it all.

**Comment by saberraz** [comment]
I filed a similar ticket for 1-n relations: https://github.com/MerginMaps/input/issues/1905

**Comment by tomasMizera** [comment]
Do we know how one can set up such a "non-existent" relation?

**Comment by saberraz** [comment]
I think, the best way to handle it:
- Show an error message in the app for the missing layer.
- Gray out the fields in the form. If you want it more useful, you can add a "missing relation" in the field title.

**Comment by PeterPetrik** [comment]
The existence of non-existent objects such as UFOs is a critical part of a daily existential question.

**Comment by tomasMizera** [comment]
Sounds like a ChatGPT :D
