### ISSUE TITLE
Mergin Maps Input 2.0.2 for Win not working due missing dependencies

### ISSUE THREAD

**Issue by PCA-Geodata** [MerginMaps/input#2610]
Installing the current version on Mergin Maps Input 2.0.2 for Win (mergin-maps-input-win64-20230222-1040.exe) seems that some dependencies are missing and the app can't start:

- geodiff.dll
- proj.dll
- qt6keychain.dll
- qca.dll

![2023-03-06_08h44_23](https://user-images.githubusercontent.com/112809095/223060904-1e5d5f29-5982-494a-8427-9a8dddc8b2db.png)
![2023-03-06_08h44_32](https://user-images.githubusercontent.com/112809095/223060908-60bbeaa4-a47f-4862-873a-54c61a50e1dc.png)
![2023-03-06_08h44_47](https://user-images.githubusercontent.com/112809095/223060909-c928b2e8-68d0-4eca-bbcc-5fa35c9ccd37.png)
![2023-03-06_08h44_56](https://user-images.githubusercontent.com/112809095/223060911-988d642a-ea3b-4d50-8cce-e4789097e6f9.png)

Uninstalling the version and downgrading to the previous release (mergin-maps-input-win64-20230203-978.exe) allow to use the app on Win.

Working on Windows 11 Pro

Thanks, 
Val

**Comment by PeterPetrik** [comment]
could be fixed by https://github.com/MerginMaps/input/commit/6f49b7c7e53c77aacf6a20f07dc8e49e6506b8a1
