### ISSUE TITLE
Problem in iOS when connecting to PostGIS

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/input#2637]
The latest release (2.1.0), PostGIS connection no longer works:
![image](https://user-images.githubusercontent.com/2649047/225336098-9bd916be-4a81-4bb7-a719-56fbe9817082.png)

**Comment by jozef-budac** [comment]
Yes, it is a problem in input 2.1.0.

![image](https://user-images.githubusercontent.com/83582181/225752433-ec457e13-2b93-4add-a5a9-723a98bd4052.png)

**Comment by jozef-budac** [comment]
yes, realized it also later. It looked similar but it was different problem.
I created test project using QGIS cloud Postgis server, but it works fine on both iOS and Android. But I need to investigate, if it is https connection
https://app.merginmaps.com/projects/input-testing/tc06_postgis/tree

**Comment by PeterPetrik** [comment]
I am thinking it may be a problem in compilation on `libpq` library, not an input packaging/building problem

**Comment by PeterPetrik** [comment]
@saberraz which project does not work?

**Comment by saberraz** [comment]
@PeterPetrik I set one up with Jozef. I will leave him recreate a new one and test. I no longer have access to the original project.
