### ISSUE TITLE
Support for text and spacer widget

### ISSUE THREAD

**Issue by CharlesGag** [MerginMaps/input#2643]
[With the text widget getting more useful since the last QGIS update](https://qgis.org/en/site/forusers/visualchangelog330/#feature-dynamic-text-widgets-with-current-value-support) I think it would be very useful to be able to use that as well for more complex forms. 

[Spacer widget as well I guess. 
](https://qgis.org/en/site/forusers/visualchangelog330/#feature-spacer-widget-for-drag-drop-attribute-forms)

Thank you

**Comment by saberraz** [comment]
And this one: https://qgis.org/en/site/forusers/visualchangelog330/#feature-data-defined-editable-state-for-form-widgets

**Comment by PeterPetrik** [comment]
https://wishlist.merginmaps.com/p/enable-new-text-space-widgets
