### ISSUE TITLE
Layer order is changed on app

### ISSUE THREAD

**Issue by velle** [MerginMaps/input#2671]
It seems that the Input app orders the layers in alphabetical order. 

Project in QGIS:
![image](https://user-images.githubusercontent.com/4488298/231512712-d19394f0-ac27-4548-bcdb-ec32050998b7.png)

Inside Input app after syncronozing project:
![image](https://user-images.githubusercontent.com/4488298/231512887-3da399eb-a30f-4e84-9c98-0d1824749abe.png)

Did I misunderstand something? Is this the intended behavior?

In my case this means that the Open Street Map covers the wfs-layer. And I don't see a way of rearranging the layers in the Input app either. 

Sincerely

```
Input App: 2.1.1 - android
System: Android (12.0)
```

```
Ubuntu 22.04.2 LTS
QGIS version: 3.22.4-Białowieża
Mergin plugin version: 2023.1 updated at Wed Feb 1 07:48:35 2023
```

**Comment by tomasMizera** [comment]
Hello @velle, this is an expected behaviour based on how Input works. Is it important for you to have the layers ordered as in QGIS?

**Comment by velle** [comment]
Thanks for responding :)

Yes the layer order is indeed important for me.

I can work around this by renaming layers and add prefixes, but I would
argue that this is both bot elegant and not in line with the behavior of
qgis, which Input leans on.

Sincerely

**Comment by PeterPetrik** [comment]
I think the layer order for rendering should be preserved from QGIS - if you change the order you may see background map on top and do not see any other data from other layers - therefore I would classify it as a bug in Input

**Comment by lefcgis** [comment]
Hi!

I have the same problem. I've already read the @PeterPetrik comment but I didn't understand. Is it possible to conserve QGIS order or not? and How do you do that?

Sincerely,


L.

**Comment by tomasMizera** [comment]
> Hi!
> 
> I have the same problem. I've already read the @PeterPetrik comment but I didn't understand. Is it possible to conserve QGIS order or not? and How do you do that?
> 
> Sincerely,
> 
> L.

Hi @lefcgis, there are two things to this order:
1. Rendering order -> the order of how layers are positioned on top of each other when rendering, e. g. background layer A is rendered below vector layer B. The rendering order here follows QGIS rendering order.
2. Order in the list of layers -> this is the list of layers that you see when clicking on the `layers` button in the app, it contains all non-private layers of the project. Layers here are sorted alphabetically.

Are you referring to the second point? In that case we sort the layers alphabetically. If you'd like to see some other behavior, I'd like to ask you to file that request to our wishlist portal here: https://wishlist.merginmaps.com/ 
Thank you!
