### ISSUE TITLE
Tour projects are deleted after closing workspace

### ISSUE THREAD

**Issue by alex-cit** [MerginMaps/input#2673]
What I did:
1. started with a clean installation of MM Input (tour projects are present when opening the app)
2. created a new project (without registration)
3. created a new account and a workspace (as prompted)
4. tried to delete this account through the app - this requires to close the workspace first, so I did
5. the **Home** tab is now empty - the tour projects are not there

![merginmaps-input-no-projects](https://user-images.githubusercontent.com/94905350/232062833-77f3277d-a701-41b7-a4d0-e49fa933d584.jpg)

Is this expected behaviour?

**Comment by tomasMizera** [comment]
Hmm, not sure, this is quite an edge case.
