### ISSUE TITLE
Hyperlink label almost invisible

### ISSUE THREAD

**Issue by Tadeo98** [MerginMaps/input#2674]
Hyperlink labels in form are almost invisible, there is very light blue used, see in the picture below:
![image](https://user-images.githubusercontent.com/94292549/232692246-d0d2484a-1cea-4b34-8dd9-3ffa776ad0ab.png)
This issue is created from https://support.lutraconsulting.co.uk/a/tickets/2078, failed to replicate the issue.
Styling does not change the colour for Input, only for QGIS.
User has his QGIS in dark mode, perhaps the light blue is a result of attempt to create better contrast of the label on dark background:
![image](https://user-images.githubusercontent.com/94292549/232693283-23e3d580-8df3-4f1f-aa99-b170663fdc69.png)

**Comment by PeterPetrik** [comment]
User manually set the color of hyperlink to light blue and we showed it that way. I think this is problem in the settings of the project, not in the mobile app.
