### ISSUE TITLE
IMPR MM: Swipe to other tab in the middle of my screen

### ISSUE THREAD

**Issue by JSoepenberg** [MerginMaps/input#2675]
Hi, 

I would like to swipe to the other tab (from tree info to other data) on my screen. Not by clicking on the other data tab, but by swiping in the middle of my screen to the right. Could you make that possible? 

![image](https://user-images.githubusercontent.com/73890345/232802586-34c92e10-8711-4448-b596-4ec0a7e3eb09.png)

![image](https://user-images.githubusercontent.com/73890345/232800964-c31b0db3-feef-4ba6-9aa5-6a74b4aed31f.png)

**Comment by tomasMizera** [comment]
Hi @JSoepenberg, thanks for your feedback! 
This used to be possible, but we needed to turn it off due to a bug in one of our core dependencies (Qt). See more here https://github.com/MerginMaps/input/issues/2473

We will enable it again once the bug is fixed :)

**Comment by tomasMizera** [comment]
Hi @JSoepenberg, 2.4.0 version (upcoming one) will have the swipe gesture enabled again :)
