### ISSUE TITLE
32 bit Input App for Windows platform

### ISSUE THREAD

**Issue by Strunge29** [MerginMaps/input#2682]
Is there a version of Input I can install on my Windows 32 bit OS powered tablet? We are a small volunteer organization working with rural communities to improve water solutions. We currently only use 32 bit windows powered tablets. We tried to install the Input app to use to collect data. It says we need a 64 bit windows OS. Why don't you make this app to be compatible with both windows platforms (32bit/64 bit). Because, frankly confining only access to 64 bit versions of windows seems to defeat the whole open source / open access intention of the project, doesn't it? Or could you provide some instructions on how a user can compile a 32 bit version for themselves if you are unwilling to build and maintain the 32 bit version as part of your project

**Comment by wonder-sk** [comment]
There is no 32-bit version of Input for Windows and we are not planning to provide support for 32-bit Windows. I am afraid your tablets are simply too old at this point. For example, QGIS project stopped creating 32-bit Windows releases back in 2021. Virtually all tablets / phones nowadays ship with 64-bit processors, so supporting 32-bit architecture would add a lot of overhead with only little added value.

It should be possible to compile 32-bit Input - see the build instructions (https://github.com/MerginMaps/input/blob/master/INSTALL.md#7-building-windows) - but you will also need to build input-sdk yourself for 32-bit.
