### ISSUE TITLE
Tapping edit icon with pen triggers identify on map

### ISSUE THREAD

**Issue by ztgis** [MerginMaps/input#2683]
I experience a strange issue when I am trying to edit a feature. When I tap the edit icon with my **finger**, it works as expected. When I tap the edit icon with the **pen**, a feature at the map behind the feature information panel is identified.

I have recorded a video that shows the issue.

https://user-images.githubusercontent.com/120651313/235968927-ca59312d-a1fc-453e-abb2-9481e7c817e1.mp4

**Comment by tomasMizera** [comment]
Hello @ztgis , thanks for reporting the issue! We will have a look at it soon.
