### ISSUE TITLE
White screen and unresponsive when adding or editing child (android)

### ISSUE THREAD

**Issue by Nathan-LloydBore** [MerginMaps/input#2684]
We have an issue on mergin (android) that seems to be getting more and more common and renders the app unusable in many instances. In short, we have a point layer with a geometry-less child. The idea being we can re-survey the same point multiple times and add new 'surveys' to it without duplicating the points. This was all working fine until around the release of Mergin 2.0 and the following error has been intermittently present since.
When we click a point and then press the pencil to edit it opens attribute form. We then click to add or edit a child feature in that form and make some changes. When we click 'done' on this child feature it then instead jumps to the edit geomoetry view of the parent. From here, we have the options to 'cancel', 'release' or 'done' and all 3 options lead to a blank white sceen popping up which cannot be interacted with at all and requires a force-closing of the app and reloading. This in turn means the edits to the child are lost.
It seems to me that when clicking 'done' on the child feature, it is clicking through to the underlying 'edit geometry' button on the parent form perhaps?

**Comment by tomasMizera** [comment]
Hello @Nathan-LloydBore, sorry to hear that! 
Based on your description, this is highly related to https://github.com/MerginMaps/input/issues/2683 and will be fixed in the upcoming release. I am closing this ticket in favour of the mentioned #2683

**Comment by Nathan-LloydBore** [comment]
I had a quick look at the video on #2683 and it is not quite the same thing. We also are not using a pen if that is relevant. I cannot get it to reproduce consistently enough to get a video or screenshots currently but will try and do so the next time it appears.

**Comment by tomasMizera** [comment]
Hi @Nathan-LloydBore, yes, it is not the very same issue, but under-the-hood, it is the same issue occurring in a different place :)
