### ISSUE TITLE
Application becomes unresponsive frequently

### ISSUE THREAD

**Issue by roya0045** [MerginMaps/input#2711]
Sometimes buttons and actions don't seem to be taken into account on ios 16.4.1 a. Turning the screen sideways can sometimes fix it.

This was observed when opening the more menu and any options didn't work but turning the screen sideways to access the option worked. Though at that point the back button didn't work when the screen was in portrait mode.

The issue can also happen when editing attributes. The logs don't show anything.

**Comment by roya0045** [comment]
@tomasMizera not sure why I didn't get the notification. The issue occurred often when editing features where the top arrows or input widget are irresposive. I also got it when opening the more menu at the bottom.

**Comment by tomasMizera** [comment]
Thanks @roya0045, I will pass this ticket to our support team, they will try to get a deeper understanding of the issue and might contact you again.

**Comment by roya0045** [comment]
I tried to look into the log but couldn't find much, at the time.

**Comment by erpas** [comment]
Hi @roya0045 is the issue related to a specific project? If yes, can you please share it with Mergin Maps support user (support@merginmaps.com)? Please follow the tutorial if in doubt:
https://merginmaps.com/docs/tutorials/working-collaboratively/#share-a-project-with-a-specific-mergin-maps-user

It would be great if you could share the diagnostic log with us as described here:
https://merginmaps.com/docs/misc/troubleshoot/#diagnostic-logs

Thanks,

Radek Pasiok
Mergin Maps Support Team

**Comment by erpas** [comment]
Also please contact us directly by email (support@merginmaps.com) if you don't want to reveal private information here on Github.
