### ISSUE TITLE
Control Visibility by Expression not working in Combination with a relations widget

### ISSUE THREAD

**Issue by rvanmaaren** [MerginMaps/input#2712]
Hi, 

I found a bug when applying a 'Control Visibility by Expression' on a groupbox in a container in combination with a relations widget. So the control visibility has the expression column = true. Within the group box, there is a relation widget to a form. The relations widget is always visible, no matter the expression (true or false). Other parent columns, columns that are in the same table as the expression, will appear and disappear by the expression.

The bug only resides in the app. In QGIS the expression works as it should, the relation widget appears and disappears with the expression.

**Comment by tomasMizera** [comment]
Hi @rvanmaaren, thanks for reporting the issue. 
I just wanted to confirm my understanding. Are you saying that it's currently not possible to hide/show the relations widget based on an expression? I would appreciate any additional information you can provide.

**Comment by rvanmaaren** [comment]
Hi @tomasMizera, That's right.

**Comment by tomasMizera** [comment]
I forwarded this issue to our support team, they will have a closer look. You can track the progress of the issue by following this ticket.

**Comment by Tadeo98** [comment]
Tested. Indeed, no matter the expression and the value used in it, with relation being present in the Group, the group is always visible (with its content).
