### ISSUE TITLE
update google APKs to use API 33

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/input#2762]
![Screenshot 2023-08-21 at 9 24 01](https://github.com/MerginMaps/input/assets/804608/84ce17e1-9e49-486c-a8df-6d547f532d7d)

**Comment by tomasMizera** [comment]
There seem to be two things to have a look at:
 - add runtime permission for notifications https://developer.android.com/about/versions/13/behavior-changes-all#notification-permission
 - there are some new rules for battery life optimisation, it would be nice to test out how the tracking behaves when MM is put into the "restricted" state https://developer.android.com/about/versions/13/behavior-changes-all#battery-resource-utilization
