### ISSUE TITLE
Database details shown on Error notification

### ISSUE THREAD

**Issue by chris9404** [MerginMaps/input#2768]
We had incorrectly added a postgres layer to a MerginMaps project and a client downloaded this version of the project.
An error then came up as follows:
![MM Error Display](https://github.com/MerginMaps/input/assets/85164641/8defd3d3-8ac6-4d34-bc31-87d2acfa30d0)

This in itself is fine, but within that error, our database details are shown, including the username and password (in the QGIS log). Even though we do not intend to use postgres layers and we only found this error because we made a mistake in including a postgres layer, we feel strongly that this error should not show database details.
![MM Error Details Edited](https://github.com/MerginMaps/input/assets/85164641/dd3cec9f-34c2-4693-b370-73e37484cf57)

**Comment by tomasMizera** [comment]
Hi @chris9404, thanks for reporting this. The logs are coming from QGIS, so you would probably see the same issue in QGIS.
We will have a deeper look and try to come up with a good solution here.

**Comment by tomasMizera** [comment]
Hi @chris9404, we checked it and it seems that storing your credentials like this is **not** recommended in QGIS due to several reasons, one of them would be that those credentials are easily exposed via logs. I will mark this one as won't fix for now. Feel free to respond / get in touch on Slack
