### ISSUE TITLE
Position tracking results in line feature with points of coordinates 0, 0 (system origin)

### ISSUE THREAD

**Issue by Tadeo98** [MerginMaps/input#2781]
On some android devices (Samsung Galaxy S20 FE, A22) when the position tracking is turned on, there is a line connecting the origin of system to the actual position provided by GPS (first picture).

When it's turned off after a while, there is no line visible in the vicinity of actual position. Although, when opening attribute table within QGIS, the line is there but it consists of points with coordinates 0, 0 (second picture).

So it seems the tracking is working but only origin point is added repeatedly, not the real position.

![image](https://github.com/MerginMaps/input/assets/94292549/f91c4169-5ac1-4ee1-b12d-ba8da2f2f530)

![image](https://github.com/MerginMaps/input/assets/94292549/7ccaeae1-0b41-4420-8bb6-dbeb43176d02)

**Comment by sttipa** [comment]
Or omething like this
![16944343845154550113003595971109](https://github.com/MerginMaps/input/assets/144282022/6272502e-b25d-43ab-8b01-68a9ab958e51)

**Comment by maellevd** [comment]
FYI, I am experiencing the same issue as described by Tadeo98 with the latest version of Mergin (2023.4.1) on Android 13 (and previous versions) on Samsung A33 and Fairphone 4.

**Comment by tomasMizera** [comment]
Will be fixed in 2.4.1 - should be released next week. A workaround is to set the system language to english (or to some other that uses `.` dots as the decimal separator)

**Comment by sttipa** [comment]
Thanks for information...Best regards....

Sent from Yahoo Mail on Android 
 
  On Fri, 27 Oct 2023 at 13:24, Tomas ***@***.***> wrote:   


Will be fixed in 2.4.1 - should be released next week. A workaround is to set the system language to english (or to some other that uses . dots as the decimal separator)

**Comment by maellevd** [comment]
Great! I confirm it's working :-)
A big thank you for fixing the bug and the feedback!

**Comment by tomasMizera** [comment]
Glad to hear that @maellevd! Thanks for confirming the fix
