### ISSUE TITLE
Use MerginMaps input on a project packaged locally or on LAN/NAS

### ISSUE THREAD

**Issue by jo-chemla** [MerginMaps/input#2796]
Hi there, 
We've got a qgis project with a lot of raster images, totaling a few dozens GBs, stored on a LAN server (a NAS which also serves the data via smb). I'd like to try MerginMaps for Android to easen drawing on a tablet. I wanted to try our the MerginMaps `Project Packaging` feature (thinking it would be similar to QField which let me package to a project that the qfield apps will be able to open), but it seems that the qgis plugin will only upload to the MerginMaps cloud storage. 
Unfortunately, the storage requirements for that project leaves Mergin cloud out of the options, hence my question: 

Is it possible to package a qgis project locally (or to a LAN/NAS share) which could then be opened in MerginMaps Input app? Do I have to spin-up a [MerginMaps Community Edition](https://merginmaps.com/docs/dev/mergince/) container to do so? 

Thanks and best regards,

**Comment by PeterPetrik** [comment]
Hi, you can package the folder manually but just having all the required files in one folder. To transfer data, you can follow https://merginmaps.com/docs/manage/missing-data/#manual-data-transfer-android , you just need to move your data to Input folder on the device via USB cable. Alternatively you can setup MM CE version. It is best to connect to Merginmaps.com/community/join to ask questions :) Enjoy the weekend

**Comment by jo-chemla** [comment]
Thanks, great to see this resource, and to know that MerginMaps can natively read qgis projects on Android! 
Not fond of communities which require an account like Slack, when information is openly accessible to anyone like here on github or your docs this is perfect! Thanks again for your time and best regards!
