### ISSUE TITLE
Pictures relation 1:N

### ISSUE THREAD

**Issue by wojtek19022** [MerginMaps/input#2816]
We've tried to make project synchronization with Postgis DB. What we did to make this happen is:
1. Configuration of project and server
2. Installation of DB-sync extension for Mergin Maps
3. Making container with Docker to make synchronization happen
4. Using GPKG file that was made using DB schema file (saved to GPKG after synchronization using Docker)
5. Made relation 1:N according to Mergin Maps documentation: https://merginmaps.com/docs/layer/attach-multiple-photos-to-features/
6. Created point and configured form to insert new data with drag&drop configuration
7. Saved automatically all changes and synchronized project with server version

After all above steps we had faced issues with saving changes correctly. Sometimes these pictures can save despite relation error:
![image](https://github.com/MerginMaps/input/assets/113895660/a988f194-4f2c-4991-9d57-d29e27cb2a78)
(the issue is on layer "Zdjęcia" and there are locations of pictures paths, thtat is GPKG file without localizations)

We've seen that Mergin Maps in this case can't operate with uuid() properly because we have to manually edit uuid by deleting last character and adding it again to make syncing work.

Hope that helped :)

**Comment by PeterPetrik** [comment]
Hi, can you please ask you question on merginmaps.com/community/join or our support channel?

**Comment by wojtek19022** [comment]
I've already asked but nobody even replied for it. I'm already on this channel and wrote directly to You but nothing and nobody helped @PeterPetrik
