### ISSUE TITLE
When using a field type of text string for dates, the values appear as blank in the app

### ISSUE THREAD

**Issue by raherin** [MerginMaps/input#2827]
When using the calendar widget to fill in date and time values in a field set to 'text string' type, dates entered show as blank in the form on the mobile app. The date and time selected will still be saved (even when 'Not null' constraints are selected) and is viewable in QGIS, but always appears as blank in the app.

**Comment by tomasMizera** [comment]
Hi @raherin, we would need a project to test it with and exact steps to reproduce it :)

**Comment by PeterPetrik** [comment]
I can reproduce it now
