### ISSUE TITLE
Tracking is not being recorded in Mergin Maps Input

### ISSUE THREAD

**Issue by maellevd** [MerginMaps/input#2856]
When I initiate tracking on the application (via Tap Start tracking), my track is not recorded (start and end times are recorded, but no line and tracked distance = 0).
However, I can record points on another layer while tracking. If I manually digitize the tracking, it works properly. 
These attempts were made on a Mergin tracking_layer without adding additional fields, and it's the same - no tracking/geometry is recorded.
I suspect it's a location/precision issue because there is a large orange line that appears, but even if I increase the precision threshold or with good accuracy, nothing changes...
 Do you have any idea what the issue might be?

![Screenshot_20231013_180043](https://github.com/MerginMaps/input/assets/37191185/d13aecf5-5e33-4a28-94a1-077e3fb6ba28)

**Comment by tomasMizera** [comment]
Hello @maellevd, thank you for reporting the issue and sorry for the inconvenience! This issue seems to be reported already here: https://github.com/MerginMaps/input/issues/2781 I will close this ticket in favour of the already existing one.
