### ISSUE TITLE
Sync from server prior to pushing from Mergin Input

### ISSUE THREAD

**Issue by Chris35Wills** [MerginMaps/input#2862]
I have a use case where a project has been prior setup to field deployment, whereby simple points will be captured with notes and a photograph. A situation has arisen where the user, using Mergin Input, has taken images at too large a file size to enable effective upload whilst in areas of more limited connectivity. Image size can be limited in the main project in QGIS (as here: https://merginmaps.com/docs/layer/settingup_forms_photo/#photos-in-mergin-maps-input), but the issue is that this has now done post-capture. These proejct changes, as far as I'm aware cannot be "pulled" without the local Input changes being pushed.

Is there a way a user with Mergin input could update their project locally with any changes made from the server, without pushing their local changes?

**Comment by PeterPetrik** [comment]
Hi, even with photo-resize option, this is applied only on new images, not already captured images. 

I think the way forward is to manually transfer project to desktop as described https://merginmaps.com/docs/manage/missing-data/ , resize photos on desktop and store it as new version from desktop. On mobile phone you can remove the project without syncing to cloud and then redownload project (with resized photos) from cloud.
