### ISSUE TITLE
Create setting to disable the "delete" button in the bottom bar of the Mergin app.

### ISSUE THREAD

**Issue by OIV-NL-QGIS** [MerginMaps/input#2869]
Case: We use the Merging app in our fire hydrant control module with great pleasure, it works very nice and smoothly. 
The inspectors test the fire hydrants and their functions for usability.

But they are never allowed! have the option to remove the fire hydrant from the map.

Therefore, we ask you whether it is possible to make the delete button in the green bottom bar adjustable with a setting so that we can indicate in the QGIS project design whether this button is shown or not shown in the green bottom bar.

Kind regards, Zaanstad NL Fire Department

**Comment by tomasMizera** [comment]
Hello @OIV-NL-QGIS, thanks for your request. Something similar is already reported in our wishlist here: https://wishlist.merginmaps.com/p/add-surveyor-permission you can add your vote there.

As a workaround for now, you can mark the layer with hydrants as "read-only" in QGIS. This way it will not be possible to add/edit/delete its features in the mobile app. Mind that we do not have the best UX for read-only layers at the moment: https://github.com/MerginMaps/input/issues/2870

**Comment by tomasMizera** [comment]
I will close this ticket, you can track the progress in the wishlist link. If you'd have any questions, do not hesitate to ask them here, in the [community slack channel](https://merginmaps.com/community/join) or in the wishlist.
