### ISSUE TITLE
2.5.0 RC - cant scroll over settings menu

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2887]
In the 2.5.0 RC when I want to check the project version, I am unable to do it, because I can't scroll in the settings menu. 
I have iPhone 6s. I didn't try it on other devices

Steps to simulate
1) in the app open a project
2) go to settings and try to scroll down -> it is not possible

**Comment by PatrikMizera** [comment]
also present on Android Xiaomi redmi 10
