### ISSUE TITLE
2.5.0 RC: Can't open project with dynamic CRS

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2891]
After the latest changes, input can't open project tc08_test_dynamic_crs with dynamic CRS. 

Description to it is: "Project CRS: EPSG:2056 - CH1903+ / LV95: Static (relies on a datum which is plate-fixed) but background map is EPSG:3857 - WGS 84 / Pseudo-Mercator: Dynamic (relies on a datum which is not plate-fixed) Based on a dynamic CRS, but no coordinate epoch is set. Coordinates are ambiguous and of limited accuracy."

Currently, this project shows error:
![image](https://github.com/MerginMaps/input/assets/83582181/e068b0d1-9898-4dfa-bb9d-0649c4d0da3e)

**Comment by PeterPetrik** [comment]
Are you sure this one is not in 2.4.0? 

Also - this may be genuine good warning that was in project all the time, but in 2.4.0 we introduced new CRS check. You project is probably wrong - as per error shown

**Comment by jozef-budac** [comment]
It is not present in 2.4.0. I know the new CRS check, but should not it be present only in case no CRS is set? And I believe this is not the case

**Comment by PeterPetrik** [comment]
@wonder-sk ?

**Comment by PeterPetrik** [comment]
related https://github.com/MerginMaps/input/issues/620

**Comment by PatrikMizera** [comment]
I was able to open up the project on Android
![Screenshot_2023-11-02-09-40-08-879_uk co lutraconsulting](https://github.com/MerginMaps/input/assets/94351263/d41fff29-577b-419d-a132-d7cbf1b859a6)
