### ISSUE TITLE
2.5.0 Can't scroll to the bottom of the workspace list

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2892]
In the latest app, the user can't scroll to the bottom of the workspace list.

Steps to reproduce
1) have a user with multiple workspaces
2) login in input and go to the workspace list
3) try to scroll to the bottom of it -> you are unable to do it

https://github.com/MerginMaps/input/assets/83582181/4a1a66bc-8b42-458e-93dd-76aeb7162bc0

**Comment by PeterPetrik** [comment]
This works in v2.4.0 iOS
