### ISSUE TITLE
2.5.0 RC: Searching of workspaces doesn't work

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/input#2893]
On the workspace page, the search doesn't work. You can insert everything there and still, all workspaces are visible. When you hit one of them, it shows an error.

1) open input and log in with an account with multiple workspaces
2) go to the workspaces page and try to search with some random string

https://github.com/MerginMaps/input/assets/83582181/d7af6d03-3f0d-4cb5-a35c-726660f2ea58

**Comment by PeterPetrik** [comment]
This works in 2.4.0 iOS
