### ISSUE TITLE
Android - the format_wfs is not loading 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#2903]
project tc06_format_wfs 

When you open the project, Input will show this error and the map will not load. 
Input 2.4.1

![Screenshot_2023-11-04-11-58-46-595_uk co lutraconsulting](https://github.com/MerginMaps/input/assets/94351263/35e16cd9-7e43-4d71-ac81-9a79aa32ce4e)

**Comment by wonder-sk** [comment]
@jozef-budac I can see you have modified the project earlier today - was it that the WFS server simply stopped publishing the originally used layer, and you switched to a different server?

**Comment by jozefbudac** [comment]
Yes, I had to change the provider to a different one. Now it is working both on mobile app and QGIS
