### ISSUE TITLE
Android - Input becomes unusable when location permission is not allowed 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/input#2904]
1. download fresh input
2. do not allow location permissions 
3. the app will either stop working or will be unusable, not showing proper info 
4. if you allow the permissions in the settings, the app will start working properly 

Input 2.4.1 

https://github.com/MerginMaps/input/assets/94351263/ce93e256-eb05-4c8a-bb35-dbe4896aaeb0

**Comment by tomasMizera** [comment]
Duplicate of #1101, related to #1057
