### ISSUE TITLE
Better evaluation of the mergin API Url

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/input#808]
when entering the URL without SSL, the ping command runs ok, but other (real) endpoints does not return correct responses. 

So when entered 
`http://test.dev.cloudmergin.com/`
it looked like I can login to the service, but once I try to open anything it jumps back to autorize windows.
`void MerginApi::authorizeFinished()` looks like `QJsonDocument` is not object. added at least the message for now in https://github.com/lutraconsulting/input/commit/aff30c1cacc22564dbc6ba7ec181942ebda4850a

**Comment by PeterPetrik** [comment]
waiting for mergin server change @varmar05

**Comment by jozef-budac** [comment]
Is this sill possible to do? When I try to user http instead of https, it shows me an error 
Internal server error during autorization.
I tested it on dev.dev.

**Comment by PeterPetrik** [comment]
with 2.1.0 it works with http too (probably correctly redirected)
